/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SkillLevelInputBean } from './skill-level-input-bean';

export interface AddSkillRequest {
    /**
     * Unique Id of assigned Contact Center
     */
    'contactCenterId': number;
    /**
     * Name of the Skill
     */
    'skillName': string;
    /**
     * List of Skill Levels to be assigned to the Skill
     */
    'skillLevels'?: Array<SkillLevelInputBean>;
    /**
     * Description of the Skill
     */
    'description'?: string;
}

