/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AppLocationMapping {
    'appId'?: string;
    'appTitle'?: string;
    'appPage'?: string;
    'ccId'?: number;
    'roles'?: Set<string>;
    'appDescription'?: string;
    'url'?: string;
    'iconUrl'?: string;
    'version'?: string;
    'enabled'?: boolean;
    'visibleEverywhere'?: boolean;
    'priority'?: number;
    'appEntityId'?: number;
}

