/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AsteriskZAPChannelEntityRequest {
    /**
     * Custom Configuration
     */
    'customConfig'?: string;
    /**
     * Asterisk ZAP Channel Entity name
     */
    'name': string;
    /**
     * Asterisk ZAP Channel Entity description
     */
    'description'?: string;
    /**
     * Number RE
     */
    'numberRE': string;
    /**
     * Voice Resource Id
     */
    'voiceResourceId': number;
    /**
     * Asterisk ZAP Channel Id
     */
    'channelId': number;
    /**
     * Hangup Cause Template Id
     */
    'hangupCauseTemplateId'?: number;
}

