/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AsteriskVoiceResourceSettingsRequest {
    /**
     * Voice Resource Id
     */
    'voiceResourceId': number;
    /**
     * Hostname
     */
    'host': string;
    /**
     * Port
     */
    'port': string;
    /**
     * Username
     */
    'user': string;
    /**
     * Secret
     */
    'secret': string;
    /**
     * AMI Permit Deny Configuration
     */
    'permitDenyConfig': string;
    /**
     * Global AMI Configuration
     */
    'globalAMIConfig': string;
    /**
     * Global SIP Configuration
     */
    'sipGlobalConfig': string;
    /**
     * Added Extension Configuration
     */
    'addedExtensionConfig'?: string;
    /**
     * Trunk Groups
     */
    'trunkGroups'?: string;
    /**
     * Trunk Type
     */
    'trunkType'?: string;
    /**
     * Global ZAP Channel Configuration
     */
    'globalZAPChannelConfig'?: string;
    /**
     * Span Count
     */
    'spanCount'?: number;
    /**
     * Failover enabled status
     */
    'failoverEnabled'?: boolean;
    /**
     * Conf AST enabled status
     */
    'confAstEnabled'?: boolean;
    /**
     * Wait timeout
     */
    'waitTimeout'?: number;
    /**
     * RTP Dumping enabled status
     */
    'isDumpRTPStat'?: boolean;
    /**
     * Codec configuration
     */
    'codecConfiguration'?: string;
}

