/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CallBackHolidayConfigurationProperty } from './call-back-holiday-configuration-property';

export interface CallBackHolidayConfiguration {
    /**
     * CallBack Holiday configuration id
     */
    'id'?: number;
    /**
     * cc/campaign are the Context for CallBack Holiday configuration
     */
    'context'?: string;
    /**
     * Context Id for CallBack Holiday configuration
     */
    'contextId'?: number;
    /**
     * CallBack Holiday configuration enabled status
     */
    'enabled'?: boolean;
    'callBackHolidayConfiguration'?: Array<CallBackHolidayConfigurationProperty>;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
}

