/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ACDNodeToAQMappingDetails } from './acdnode-to-aqmapping-details';

export interface CampaignFeatureContextInfoWithoutNodeFlowData {
    'id'?: number;
    'campaignId'?: number;
    'name'?: string;
    'nodeflowType'?: string;
    'nodeflowMetaData'?: string;
    'signature'?: string;
    'transferrable'?: boolean;
    'acdNodeToAqMapping'?: Array<ACDNodeToAQMappingDetails>;
}

