/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ChatCampaignSettingRequest {
    /**
     * Campaign Id for chat campaign settings
     */
    'campaignId': number;
    /**
     * CRM Url
     */
    'crmUrl'?: string;
    /**
     * Preview Url
     */
    'previewUrl'?: string;
    /**
     * Disposition Url
     */
    'dispositionUrl'?: string;
    /**
     * Peak Chat Count
     */
    'peakChatCount': number;
    /**
     * Number of last chats to monitor
     */
    'numLastChatsToMonitor': number;
    /**
     * Wrap timeout for chat
     */
    'wrapTimeout': number;
    /**
     * chat logs enabled
     */
    'chatLogsEnabled': boolean;
    /**
     * should Show Chat Log
     */
    'shouldShowChatLog'?: boolean;
}

