/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ClientSessionTimeout {
    /**
     * unique id of the HttpsConfiguration
     */
    'id'?: number;
    /**
     * timeout in milliseconds
     */
    'timeout'?: number;
    /**
     * name of client
     */
    'clientType'?: string;
    /**
     * userType
     */
    'userType'?: string;
    /**
     * Contact Center ID (optional)
     */
    'ccId'?: number;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
}

