/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ContactCenterRoutingProfileContactCenterRoutingProfileRowPlanSetInner } from './contact-center-routing-profile-contact-center-routing-profile-row-plan-set-inner';

export interface ContactCenterRoutingProfile {
    /**
     * Id of contact center routing profile
     */
    'id'?: number;
    /**
     * contact center routing profile name
     */
    'name'?: string;
    /**
     * contact center routing profile type
     */
    'type'?: string;
    /**
     * Contact center id
     */
    'contactCenterId'?: number;
    /**
     * Routing profile plans
     */
    'contactCenterRoutingProfileRowPlanSet'?: Array<ContactCenterRoutingProfileContactCenterRoutingProfileRowPlanSetInner>;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
}

