/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ContactCenterRoutingPolicyRequest {
    /**
     * type of contact center routing policy
     */
    'policyType': string;
    /**
     * name of contact center routing policy
     */
    'policyName': string;
    /**
     * contact center id
     */
    'contactCenterId': number;
    /**
     * Assigned profile id list
     */
    'contactCenterRoutingProfileIds'?: Array<number>;
}

