/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ContactCenterCallContextDetailOutputRequest {
    /**
     * Unique Id of Contact Center Call Context
     */
    'id'?: number;
    /**
     * Unique Id of assigned Contact Center
     */
    'contactCenterId'?: number;
    /**
     * Unique Id of Call Context
     */
    'callContextId'?: number;
    /**
     * Maximum Number of Outbound Calls allowed
     */
    'maxOutboundCalls'?: number;
    /**
     * Maximum Number of Inbound Calls allowed
     */
    'maxInboundCalls'?: number;
    /**
     * Maximum Number of Total Active Calls allowed
     */
    'maxTotalActiveCalls'?: number;
    /**
     * Voice Resource Id
     */
    'voiceResourceId'?: number;
    /**
     * Outgoing allowed status
     */
    'allowOutgoing'?: boolean;
    /**
     * Incoming allowed status
     */
    'allowIncoming'?: boolean;
    /**
     * Asterisk Entity name
     */
    'entityName'?: string;
    /**
     * Call Context name
     */
    'callContextName'?: string;
    'local'?: boolean;
    'endPoint'?: boolean;
}

