/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KpiOption } from './kpi-option';

export interface CreateKpiResponseDto {
    /**
     * Unique identifier of the KPI
     */
    'id'?: string;
    /**
     * Name of the KPI
     */
    'kpiName'?: string;
    /**
     * Question text for the KPI
     */
    'kpiQuestion'?: string;
    /**
     * Help text for the KPI
     */
    'helpText'?: string;
    /**
     * Input type for the KPI
     */
    'inputType'?: string;
    /**
     * Available options for the KPI
     */
    'options'?: Array<KpiOption>;
    /**
     * Whether the KPI is critical
     */
    'isCritical'?: boolean;
    /**
     * Whether the KPI is mandatory
     */
    'isMandatory'?: boolean;
    /**
     * Whether comment is mandatory for this KPI
     */
    'isCommentMandatory'?: boolean;
    /**
     * Whether dispute is allowed for this KPI
     */
    'isDisputeAllowed'?: boolean;
    /**
     * Whether scoring is allowed for this KPI
     */
    'isScoringAllowed'?: boolean;
    /**
     * Weightage for the KPI
     */
    'weightage'?: number;
}

