/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateSubCategoryResponseDto {
    /**
     * Unique identifier of the sub category
     */
    'id'?: string;
    /**
     * Name of the sub category
     */
    'name'?: string;
    /**
     * Description of the sub category
     */
    'description'?: string;
    /**
     * Whether the sub category is deleted
     */
    'isDeleted'?: boolean;
    /**
     * Creation timestamp
     */
    'createdAt'?: string;
    /**
     * Profile ID
     */
    'profileId'?: string;
    /**
     * Category ID
     */
    'categoryId'?: string;
}

