/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DashboardContext } from './dashboard-context';

export interface DashboardRoleRequest {
    /**
     * Operation to perform: ASSIGN_ROLE or UNASSIGN_ROLE
     */
    'operation': DashboardRoleRequestOperationEnum;
    /**
     * Role like Supervisor, Agent
     */
    'userType': Array<string>;
    /**
     * UI slot where the dashboard should be placed: HOME_DASHBOARD, ANALYTICS_DASHBOARD, or REPORTS_DASHBOARD
     */
    'slot': DashboardRoleRequestSlotEnum;
    /**
     * List of RLS (Row Level Security) filters to be applied. Required for assign-role, optional for unassign-role.
     */
    'rls'?: Array<DashboardRoleRequestRlsEnum>;
    /**
     * List of context mappings to be applied. Optional for both assign and unassign operations.
     */
    'context'?: Array<DashboardContext>;
}

export const DashboardRoleRequestOperationEnum = {
    AssignRole: 'ASSIGN_ROLE',
    UnassignRole: 'UNASSIGN_ROLE',
} as const;

export type DashboardRoleRequestOperationEnum = typeof DashboardRoleRequestOperationEnum[keyof typeof DashboardRoleRequestOperationEnum];
export const DashboardRoleRequestSlotEnum = {
    HomeDashboard: 'HOME_DASHBOARD',
    AnalyticsDashboard: 'ANALYTICS_DASHBOARD',
    ReportsDashboard: 'REPORTS_DASHBOARD',
} as const;

export type DashboardRoleRequestSlotEnum = typeof DashboardRoleRequestSlotEnum[keyof typeof DashboardRoleRequestSlotEnum];
export const DashboardRoleRequestRlsEnum = {
    UserId: 'USER_ID',
    UserName: 'USER_NAME',
    UserType: 'USER_TYPE',
    CampaignId: 'CAMPAIGN_ID',
    CampaignName: 'CAMPAIGN_NAME',
    ProcessId: 'PROCESS_ID',
} as const;

export type DashboardRoleRequestRlsEnum = typeof DashboardRoleRequestRlsEnum[keyof typeof DashboardRoleRequestRlsEnum];


