/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DetailedHangupCause {
    /**
     * Detailed Hangup Cause Id
     */
    'id'?: number;
    /**
     * Hangup Cause Template Id
     */
    'templateId'?: number;
    /**
     * Detailed Hangup Cause Description
     */
    'detailedHangupCauseDescription'?: string;
    /**
     * Detailed Hangup Cause Code
     */
    'detailedHangupCauseCode'?: number;
    /**
     * Entity type
     */
    'entityType'?: string;
    /**
     * Call Manager Hangup Cause
     */
    'callManagerHangupCause'?: string;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
    'userHangupCauseCode'?: number;
    'userHangupCauseDescription'?: string;
}

