/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DIDGroupConfiguration {
    /**
     * unique id of DID group
     */
    'id'?: number;
    /**
     * associated campaign id
     */
    'campaignId'?: number;
    /**
     * associated process id
     */
    'processId'?: number;
    /**
     * associated cc id
     */
    'ccId'?: number;
    /**
     * name assigned to group
     */
    'groupName'?: string;
    /**
     * priority assigned to group
     */
    'priority'?: number;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
    'active'?: boolean;
}

