/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DispositionAttemptRetrySetting } from './disposition-attempt-retry-setting';

export interface DispositionClassAttemptRetrySetting {
    /**
     * Unique Id of Disposition Class Attempt Retry Setting
     */
    'id'?: number;
    /**
     * Disposition Class Id
     */
    'dispositionCodeId'?: number;
    /**
     * Attempt Vs Retry Settings
     */
    'attemptVsAttemptRetrySettingBeans'?: { [key: string]: DispositionAttemptRetrySetting; };
    /**
     * Max Sequence Attempt
     */
    'maxSequentialAttempt'?: number;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
}

