/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DomainAuthConfigurationRequest {
    /**
     * domainName
     */
    'domainName': string;
    /**
     * consumerId
     */
    'consumerId'?: number;
    /**
     * serviceProvider
     */
    'serviceProvider'?: string;
}

