/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Duplicate action request
 */
export interface DuplicateDataExtractorRequestDto {
    /**
     * Action to perform - must be \'duplicate\'
     */
    'action': DuplicateDataExtractorRequestDtoActionEnum;
}

export const DuplicateDataExtractorRequestDtoActionEnum = {
    Duplicate: 'duplicate',
} as const;

export type DuplicateDataExtractorRequestDtoActionEnum = typeof DuplicateDataExtractorRequestDtoActionEnum[keyof typeof DuplicateDataExtractorRequestDtoActionEnum];


