/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface EmailNotificationConfigurationRequest {
    /**
     * Email Notification Configuration Id
     */
    'id'?: number;
    /**
     * Email Notification Configuration Context Type
     */
    'contextType': string;
    /**
     * Email Notification Configuration Context Id
     */
    'contextId': number;
    /**
     * Notification Type
     */
    'notificationType'?: string;
    /**
     * Event Type
     */
    'eventType'?: string;
    /**
     * Email Notification enabled status
     */
    'value'?: boolean;
    /**
     * Email Notification Template Id
     */
    'templateId'?: number;
    /**
     * Media Profile Id
     */
    'mediaProfileId'?: string;
    /**
     * Alternate Media Profile Id
     */
    'alternateMediaProfileId'?: string;
    /**
     * Email Notification Template Id
     */
    'templateSubject'?: string;
    /**
     * Email Notification Template Id
     */
    'templateBody'?: string;
}

