/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface MaskingPolicyUpdateResponse {
    /**
     * Process Id
     */
    'processId'?: number;
    /**
     * Contact Center Id
     */
    'contactCenterId'?: number;
    /**
     * Masking Policy Type
     */
    'policyType'?: MaskingPolicyUpdateResponsePolicyTypeEnum;
    /**
     * Masking Policy Properties
     */
    'policyProperties'?: { [key: string]: string; };
    /**
     * Process Name
     */
    'processName'?: string;
    /**
     * Masking Policy Update Status
     */
    'status'?: string;
}

export const MaskingPolicyUpdateResponsePolicyTypeEnum = {
    RandomNumberMaskingPolicy: 'RANDOM_NUMBER_MASKING_POLICY',
    ReplacementMaskingPolicy: 'REPLACEMENT_MASKING_POLICY',
    None: 'NONE',
} as const;

export type MaskingPolicyUpdateResponsePolicyTypeEnum = typeof MaskingPolicyUpdateResponsePolicyTypeEnum[keyof typeof MaskingPolicyUpdateResponsePolicyTypeEnum];


