/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OTPConfiguration {
    /**
     * Unique Id
     */
    'id'?: number;
    /**
     * Contact Center Id
     */
    'contactCenterId'?: number;
    /**
     * Password Recovery Parameter
     */
    'isPasswordRecoveryEnabled'?: boolean;
    /**
     * OTP Type
     */
    'otpType'?: string;
    /**
     * OTP Expiry
     */
    'otpExpiry'?: number;
    /**
     * List of Delivery Channels
     */
    'deliveryChannelIds'?: Array<number>;
    /**
     * Notification Body
     */
    'notificationBody'?: string;
    /**
     * Notification Subject
     */
    'notificationSubject'?: string;
    /**
     * Max Retries
     */
    'maxRetries'?: number;
    /**
     * OTP Context (PASSWORD_RECOVERY or TWO_FACTOR_AUTHENTICATION)
     */
    'otpContext'?: string;
    /**
     * Entity date added
     */
    'dateAdded'?: string;
    /**
     * Entity date modified
     */
    'dateModified'?: string;
    /**
     * Patch version of the entity
     */
    'ref'?: number;
    /**
     * Schema version of the entity
     */
    'version'?: number;
}

