/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TemplateColumnDefinitionEntity } from './template-column-definition-entity';

export interface TemplateColumnDefinition {
    /**
     * Template ID
     */
    'templateDefinitionId'?: number;
    /**
     * Column Definition ID
     */
    'columnDefinitionId'?: number;
    /**
     * Whether the Column is Primary Key or Not
     */
    'primaryKey'?: boolean;
    /**
     * Whether the Column is Nullable or Not
     */
    'nullable'?: boolean;
    /**
     * Whether the Column is Unique or Not
     */
    'isUnique'?: boolean;
    /**
     * Whether the Column is Composite or Not
     */
    'isComposite'?: boolean;
    'entity'?: TemplateColumnDefinitionEntity;
}

