/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TemplateColumnDefinition } from './template-column-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { TemplateColumnDefinitionId } from './template-column-definition-id';

export interface TemplateColumnDefinitionEntity {
    'id'?: TemplateColumnDefinitionId;
    'primaryKey'?: boolean;
    'nullable'?: boolean;
    'isUnique'?: boolean;
    'isComposite'?: boolean;
    'beanFromEntity'?: TemplateColumnDefinition;
    'idString'?: string;
}

