/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TenantCleanupConfiguration } from './tenant-cleanup-configuration';

export interface TenantCleanupConfigurationEntity {
    'id'?: number;
    'ccId'?: number;
    'tableType'?: TenantCleanupConfigurationEntityTableTypeEnum;
    'intervalInMonths'?: number;
    'batchSizeInMinutes'?: number;
    'batchCountInDays'?: number;
    'sleepIntervalInMs'?: number;
    'dateAdded'?: string;
    'dateModified'?: string;
    'ref'?: number;
    'version'?: number;
    'beanFromEntity'?: TenantCleanupConfiguration;
    'idString'?: string;
}

export const TenantCleanupConfigurationEntityTableTypeEnum = {
    Interval: 'INTERVAL',
    Summary: 'SUMMARY',
} as const;

export type TenantCleanupConfigurationEntityTableTypeEnum = typeof TenantCleanupConfigurationEntityTableTypeEnum[keyof typeof TenantCleanupConfigurationEntityTableTypeEnum];


