/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateCustomConfigurationRequest {
    /**
     * context of the related custom configuration. Context can be any string to support custom hierarchies
     */
    'contextType': string;
    /**
     * context ID of the related custom configuration
     */
    'contextId': number;
    /**
     * Name of the related custom configuration
     */
    'name': string;
    /**
     * key Data pair list associated with the related custom configuration, length must be between 1-200
     */
    'keyVsData': { [key: string]: string; };
}

