/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface VoicePromptWithStatusResponse {
    'voicePromptId'?: number;
    'voicePromptName'?: string;
    'ownerUserId'?: string;
    'fileName'?: string;
    'relativePath'?: string;
    'campaignId'?: number;
    'status'?: string;
}

