/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LeadDetailBean } from './lead-detail-bean';

export interface DashboardLeadData {
    'minLeadPenetrationRate'?: number;
    'leadNameWithMinPenetration'?: string;
    'leadNameVsPenetrationStatus'?: { [key: string]: { [key: string]: number; }; };
    'leadDetailBean'?: Array<LeadDetailBean>;
    'statsCalculatedTime'?: string;
}

