/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OverallCallDistributionDetail {
    /**
     * No. of status count
     */
    'count'?: number;
    /**
     * No. of status transferred
     */
    'transfer'?: number;
    /**
     * No. of status not transferred
     */
    'nonTransfer'?: number;
    /**
     * Percentage of transferred status
     */
    'transferPercent'?: number;
    /**
     * Percentage of non transferred status
     */
    'nonTransferPercent'?: number;
}

