/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stats Configuration
 */
export interface StatsConfigRequest {
    /**
     * retention period in days
     */
    'retentionPeriod': number;
    /**
     * Name of Custom Stat to be created
     */
    'name': string;
    /**
     * List of primary keys,contact_center_id and interval_start_time are added by default
     */
    'primaryKeys': Array<string>;
    /**
     * custom stats table columns
     */
    'tableColumns': Array<string>;
    /**
     * Name of column to partition table with
     */
    'partitionColumn': string;
}

