/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserSessionRawRecalculateRequest {
    'startDate'?: string;
    'endDate'?: string;
    'sessionId'?: string;
    'state'?: UserSessionRawRecalculateRequestStateEnum;
}

export const UserSessionRawRecalculateRequestStateEnum = {
    Processed: 'PROCESSED',
    Unprocessed: 'UNPROCESSED',
    Error: 'ERROR',
} as const;

export type UserSessionRawRecalculateRequestStateEnum = typeof UserSessionRawRecalculateRequestStateEnum[keyof typeof UserSessionRawRecalculateRequestStateEnum];


