/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserSessionInfo {
    /**
     * Associated contact center id
     */
    'contactCenterId'?: number;
    /**
     * Unique ID of the user
     */
    'userId'?: string;
    /**
     * Session id of the user
     */
    'userSessionId'?: string;
}

