/* tslint:disable */
/* eslint-disable */
/**
 * Data Engine
 * Collection of all Data Engine Requests which comprises of Reports, Stats, Monitoring and VLA Requests
 *
 * The version of the OpenAPI document: v6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PhoneInfo } from './phone-info';

export interface UserCallRuntimeInfo {
    /**
     * Campaign Id for which the queue is mapped
     */
    'status'?: string;
    'numCallMembers'?: number;
    'contactCenterId'?: number;
    'userId'?: string;
    'userName'?: string;
    'userType'?: string;
    'callContextId'?: number;
    'phoneInfo'?: PhoneInfo;
    'statusChangeTime'?: string;
    'reason'?: string;
}

