import { UserType } from "./types";

/**
 * Roles permitted to log in through this interface. Any role outside this list
 * is rejected after authentication and asked to use the standard portal.
 */
export const ALLOWED_ROLES: readonly UserType[] = [
  UserType.ADMIN,
  UserType.SUPERVISOR,
];

/**
 * Login API failure error codes.
 * Add any new error code here and reference it from the auth flow.
 */
export const LOGIN_ERROR_CODE = {
  INVALID_LICENSE_CODE: 99099,
  USER_ACCOUNT_TEMPORARY_BLOCKED: 70020,
  USER_ACCOUNT_PERMANENT_BLOCKED: 70021,
  INVALID_REQUEST_WITH_SSO: 70022,
  DISALLOW_AFTER_LIMIT_ERROR_CODE: 20207,

  FORCE_LOGIN_ERROR_CODE: 20201,
  INVALID_AUTHENTICATION: 20203,
  CAPTCHA_REQUIRED: 20206,
  INVALID_CAPTCHA: 20205,
  SESSION_EXCEPTION: 0,
  USERTYPE_NOT_ALLOWED_IN_CURRENT_MODE: 20202,

  // Token authentication related exceptions
  TOKEN_AUTH_POLICY_AUTH_API_INVALID_TOKEN: 70041,
  TOKEN_AUTH_POLICY_AUTH_API_FAILED: 70042,
  TOKEN_AUTH_POLICY_AUTH_API_REQUEST_TIMEOUT: 70043,
  TOKEN_AUTH_POLICY_AUTH_API_SERVICE_DOWN: 70044,
  TOKEN_AUTH_POLICY_AUTH_API_INVALID_USER_ID: 70045,
  TOKEN_AUTH_POLICY_INVALID_USER_ID: 70046,
  TOKEN_AUTH_POLICY_AUTH_TOKEN_NOT_PROVIDED: 70047,

  // Used when the middleware proxy fails
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_NULL_RESPONSE: 70051,
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_INVALID_RESPONSE: 70052,
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_FAILURE: 70053,
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_CONNECTION_TIMEOUT: 70054,
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_SOCKET_TIMEOUT: 70055,
  TOKEN_AUTH_POLICY_AUTH_API_PROXY_SERVICE_DOWN: 70056,

  TOKEN_AUTH_POLICY_CC_ID_NOT_PROVIDED: 70061,
  TOKEN_AUTH_POLICY_TOKEN_AUTH_CONF_NOT_CONFIGURED: 70062,
  TOKEN_AUTH_POLICY_TOKEN_CONF_INVALID: 70063,

  OTP_AUTH_POLICY_REGENERATE_LIMIT_REACHED: 80001,

  FILTER_GROUP_ENABLE_FAILED_ERROR_CODE: 10,

  LDAP_AUTHENTICATION_FAILED_EXCEPTION: 20209,
  LDAP_CREDENTIAL_FAILED_EXCEPTION: 20210,
  ROLE_NOT_ALLOWED_DIRECT_LOGIN: 90001,
} as const;
