/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddAgentQueueRequest } from '../models';
// @ts-ignore
import type { AgentQueue } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { ModifyAgentQueueRequest } from '../models';
// @ts-ignore
import type { QueueDetailBean } from '../models';
/**
 * AgentQueueApi - axios parameter creator
 */
export const AgentQueueApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Agent Queue with given data
         * @summary Add Agent Queue
         * @param {AddAgentQueueRequest} addAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAgentQueue: async (addAgentQueueRequest: AddAgentQueueRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addAgentQueueRequest' is not null or undefined
            assertParamExists('addAgentQueue', 'addAgentQueueRequest', addAgentQueueRequest)
            const localVarPath = `/hierarchyconfig/agentQueue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addAgentQueueRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Assign Skill to the given Agent Queue
         * @summary Assign Skill To Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be assigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSkillsToAgentQueue: async (agentQueueId: number, skillIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueId' is not null or undefined
            assertParamExists('assignSkillsToAgentQueue', 'agentQueueId', agentQueueId)
            // verify required parameter 'skillIds' is not null or undefined
            assertParamExists('assignSkillsToAgentQueue', 'skillIds', skillIds)
            const localVarPath = `/hierarchyconfig/agentQueue/{agentQueueId}/skill/assignSkillsToAgentQueue`
                .replace('{agentQueueId}', encodeURIComponent(String(agentQueueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (skillIds) {
                localVarQueryParameter['skillIds'] = skillIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Agent Queue for the given Id
         * @summary Get Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAgentQueueDetailed: async (agentQueueId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueId' is not null or undefined
            assertParamExists('getAgentQueueDetailed', 'agentQueueId', agentQueueId)
            const localVarPath = `/hierarchyconfig/agentQueue/{agentQueueId}`
                .replace('{agentQueueId}', encodeURIComponent(String(agentQueueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify Agent Queue with the given details
         * @summary Modify Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {ModifyAgentQueueRequest} modifyAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyAgentQueue: async (agentQueueId: number, modifyAgentQueueRequest: ModifyAgentQueueRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueId' is not null or undefined
            assertParamExists('modifyAgentQueue', 'agentQueueId', agentQueueId)
            // verify required parameter 'modifyAgentQueueRequest' is not null or undefined
            assertParamExists('modifyAgentQueue', 'modifyAgentQueueRequest', modifyAgentQueueRequest)
            const localVarPath = `/hierarchyconfig/agentQueue/{agentQueueId}`
                .replace('{agentQueueId}', encodeURIComponent(String(agentQueueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modifyAgentQueueRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Agent Queue for the given Id
         * @summary Remove Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAgentQueue: async (agentQueueId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueId' is not null or undefined
            assertParamExists('removeAgentQueue', 'agentQueueId', agentQueueId)
            const localVarPath = `/hierarchyconfig/agentQueue/{agentQueueId}`
                .replace('{agentQueueId}', encodeURIComponent(String(agentQueueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove All Agent Queue for the given Ids
         * @summary Remove Agent Queues
         * @param {Array<number>} agentQueueIds List of Agent Queue Ids to be removed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAllAgentQueues: async (agentQueueIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueIds' is not null or undefined
            assertParamExists('removeAllAgentQueues', 'agentQueueIds', agentQueueIds)
            const localVarPath = `/hierarchyconfig/agentQueue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (agentQueueIds) {
                localVarQueryParameter['agentQueueIds'] = agentQueueIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unassign Skill from the given Agent Queue
         * @summary Unassign Skill From Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignSkillsFromAgentQueue: async (agentQueueId: number, skillIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentQueueId' is not null or undefined
            assertParamExists('unassignSkillsFromAgentQueue', 'agentQueueId', agentQueueId)
            // verify required parameter 'skillIds' is not null or undefined
            assertParamExists('unassignSkillsFromAgentQueue', 'skillIds', skillIds)
            const localVarPath = `/hierarchyconfig/agentQueue/{agentQueueId}/skill/unassignSkillsFromAgentQueue`
                .replace('{agentQueueId}', encodeURIComponent(String(agentQueueId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (skillIds) {
                localVarQueryParameter['skillIds'] = skillIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AgentQueueApi - functional programming interface
 */
export const AgentQueueApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AgentQueueApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Agent Queue with given data
         * @summary Add Agent Queue
         * @param {AddAgentQueueRequest} addAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAgentQueue(addAgentQueueRequest: AddAgentQueueRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AgentQueue>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAgentQueue(addAgentQueueRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.addAgentQueue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Assign Skill to the given Agent Queue
         * @summary Assign Skill To Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be assigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignSkillsToAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignSkillsToAgentQueue(agentQueueId, skillIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.assignSkillsToAgentQueue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Agent Queue for the given Id
         * @summary Get Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAgentQueueDetailed(agentQueueId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueueDetailBean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAgentQueueDetailed(agentQueueId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.getAgentQueueDetailed']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify Agent Queue with the given details
         * @summary Modify Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {ModifyAgentQueueRequest} modifyAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyAgentQueue(agentQueueId: number, modifyAgentQueueRequest: ModifyAgentQueueRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AgentQueue>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyAgentQueue(agentQueueId, modifyAgentQueueRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.modifyAgentQueue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Agent Queue for the given Id
         * @summary Remove Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeAgentQueue(agentQueueId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeAgentQueue(agentQueueId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.removeAgentQueue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove All Agent Queue for the given Ids
         * @summary Remove Agent Queues
         * @param {Array<number>} agentQueueIds List of Agent Queue Ids to be removed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeAllAgentQueues(agentQueueIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeAllAgentQueues(agentQueueIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.removeAllAgentQueues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unassign Skill from the given Agent Queue
         * @summary Unassign Skill From Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unassignSkillsFromAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unassignSkillsFromAgentQueue(agentQueueId, skillIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AgentQueueApi.unassignSkillsFromAgentQueue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AgentQueueApi - factory interface
 */
export const AgentQueueApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AgentQueueApiFp(configuration)
    return {
        /**
         * Add Agent Queue with given data
         * @summary Add Agent Queue
         * @param {AddAgentQueueRequest} addAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAgentQueue(addAgentQueueRequest: AddAgentQueueRequest, options?: RawAxiosRequestConfig): AxiosPromise<AgentQueue> {
            return localVarFp.addAgentQueue(addAgentQueueRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Assign Skill to the given Agent Queue
         * @summary Assign Skill To Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be assigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignSkillsToAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.assignSkillsToAgentQueue(agentQueueId, skillIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Agent Queue for the given Id
         * @summary Get Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAgentQueueDetailed(agentQueueId: number, options?: RawAxiosRequestConfig): AxiosPromise<QueueDetailBean> {
            return localVarFp.getAgentQueueDetailed(agentQueueId, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify Agent Queue with the given details
         * @summary Modify Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {ModifyAgentQueueRequest} modifyAgentQueueRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyAgentQueue(agentQueueId: number, modifyAgentQueueRequest: ModifyAgentQueueRequest, options?: RawAxiosRequestConfig): AxiosPromise<AgentQueue> {
            return localVarFp.modifyAgentQueue(agentQueueId, modifyAgentQueueRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Agent Queue for the given Id
         * @summary Remove Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAgentQueue(agentQueueId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeAgentQueue(agentQueueId, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove All Agent Queue for the given Ids
         * @summary Remove Agent Queues
         * @param {Array<number>} agentQueueIds List of Agent Queue Ids to be removed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAllAgentQueues(agentQueueIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeAllAgentQueues(agentQueueIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Unassign Skill from the given Agent Queue
         * @summary Unassign Skill From Agent Queue
         * @param {number} agentQueueId Unique Id of Agent Queue
         * @param {Array<number>} skillIds List of Skill Ids to be unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignSkillsFromAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unassignSkillsFromAgentQueue(agentQueueId, skillIds, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AgentQueueApi - object-oriented interface
 */
export class AgentQueueApi extends BaseAPI {
    /**
     * Add Agent Queue with given data
     * @summary Add Agent Queue
     * @param {AddAgentQueueRequest} addAgentQueueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addAgentQueue(addAgentQueueRequest: AddAgentQueueRequest, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).addAgentQueue(addAgentQueueRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Assign Skill to the given Agent Queue
     * @summary Assign Skill To Agent Queue
     * @param {number} agentQueueId Unique Id of Agent Queue
     * @param {Array<number>} skillIds List of Skill Ids to be assigned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignSkillsToAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).assignSkillsToAgentQueue(agentQueueId, skillIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Agent Queue for the given Id
     * @summary Get Agent Queue
     * @param {number} agentQueueId Unique Id of Agent Queue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAgentQueueDetailed(agentQueueId: number, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).getAgentQueueDetailed(agentQueueId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify Agent Queue with the given details
     * @summary Modify Agent Queue
     * @param {number} agentQueueId Unique Id of Agent Queue
     * @param {ModifyAgentQueueRequest} modifyAgentQueueRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyAgentQueue(agentQueueId: number, modifyAgentQueueRequest: ModifyAgentQueueRequest, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).modifyAgentQueue(agentQueueId, modifyAgentQueueRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Agent Queue for the given Id
     * @summary Remove Agent Queue
     * @param {number} agentQueueId Unique Id of Agent Queue
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeAgentQueue(agentQueueId: number, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).removeAgentQueue(agentQueueId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove All Agent Queue for the given Ids
     * @summary Remove Agent Queues
     * @param {Array<number>} agentQueueIds List of Agent Queue Ids to be removed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeAllAgentQueues(agentQueueIds: Array<number>, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).removeAllAgentQueues(agentQueueIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unassign Skill from the given Agent Queue
     * @summary Unassign Skill From Agent Queue
     * @param {number} agentQueueId Unique Id of Agent Queue
     * @param {Array<number>} skillIds List of Skill Ids to be unassigned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unassignSkillsFromAgentQueue(agentQueueId: number, skillIds: Array<number>, options?: RawAxiosRequestConfig) {
        return AgentQueueApiFp(this.configuration).unassignSkillsFromAgentQueue(agentQueueId, skillIds, options).then((request) => request(this.axios, this.basePath));
    }
}

