/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AppCCMapping } from '../models';
// @ts-ignore
import type { AppCCMappingRequest } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
/**
 * AppFrameworkAppCCMappingApi - axios parameter creator
 */
export const AppFrameworkAppCCMappingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Save App CC Mapping
         * @summary Save App CC Mapping
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAppCCMapping: async (appCCMappingRequest: AppCCMappingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appCCMappingRequest' is not null or undefined
            assertParamExists('addAppCCMapping', 'appCCMappingRequest', appCCMappingRequest)
            const localVarPath = `/appfw/app/ccmapping/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(appCCMappingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get App 
         * @summary Get App CC Mapping
         * @param {string} appId app id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppCCMapping: async (appId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appId' is not null or undefined
            assertParamExists('getAppCCMapping', 'appId', appId)
            const localVarPath = `/appfw/app/ccmapping/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (appId !== undefined) {
                localVarQueryParameter['appId'] = appId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete App CC Mapping
         * @summary Delete App CC Mapping
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAppCCMapping: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removeAppCCMapping', 'id', id)
            const localVarPath = `/appfw/app/ccmapping/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update App CC Mapping 
         * @summary Update App CC Mapping
         * @param {number} id 
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppCCMapping: async (id: number, appCCMappingRequest: AppCCMappingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAppCCMapping', 'id', id)
            // verify required parameter 'appCCMappingRequest' is not null or undefined
            assertParamExists('updateAppCCMapping', 'appCCMappingRequest', appCCMappingRequest)
            const localVarPath = `/appfw/app/ccmapping/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(appCCMappingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppFrameworkAppCCMappingApi - functional programming interface
 */
export const AppFrameworkAppCCMappingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppFrameworkAppCCMappingApiAxiosParamCreator(configuration)
    return {
        /**
         * Save App CC Mapping
         * @summary Save App CC Mapping
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAppCCMapping(appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppCCMapping>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAppCCMapping(appCCMappingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppFrameworkAppCCMappingApi.addAppCCMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get App 
         * @summary Get App CC Mapping
         * @param {string} appId app id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAppCCMapping(appId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AppCCMapping>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAppCCMapping(appId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppFrameworkAppCCMappingApi.getAppCCMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete App CC Mapping
         * @summary Delete App CC Mapping
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeAppCCMapping(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeAppCCMapping(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppFrameworkAppCCMappingApi.removeAppCCMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update App CC Mapping 
         * @summary Update App CC Mapping
         * @param {number} id 
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAppCCMapping(id: number, appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AppCCMapping>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAppCCMapping(id, appCCMappingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppFrameworkAppCCMappingApi.updateAppCCMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppFrameworkAppCCMappingApi - factory interface
 */
export const AppFrameworkAppCCMappingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppFrameworkAppCCMappingApiFp(configuration)
    return {
        /**
         * Save App CC Mapping
         * @summary Save App CC Mapping
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAppCCMapping(appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppCCMapping> {
            return localVarFp.addAppCCMapping(appCCMappingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get App 
         * @summary Get App CC Mapping
         * @param {string} appId app id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAppCCMapping(appId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<AppCCMapping>> {
            return localVarFp.getAppCCMapping(appId, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete App CC Mapping
         * @summary Delete App CC Mapping
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAppCCMapping(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeAppCCMapping(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update App CC Mapping 
         * @summary Update App CC Mapping
         * @param {number} id 
         * @param {AppCCMappingRequest} appCCMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAppCCMapping(id: number, appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig): AxiosPromise<AppCCMapping> {
            return localVarFp.updateAppCCMapping(id, appCCMappingRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppFrameworkAppCCMappingApi - object-oriented interface
 */
export class AppFrameworkAppCCMappingApi extends BaseAPI {
    /**
     * Save App CC Mapping
     * @summary Save App CC Mapping
     * @param {AppCCMappingRequest} appCCMappingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addAppCCMapping(appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig) {
        return AppFrameworkAppCCMappingApiFp(this.configuration).addAppCCMapping(appCCMappingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get App 
     * @summary Get App CC Mapping
     * @param {string} appId app id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAppCCMapping(appId: string, options?: RawAxiosRequestConfig) {
        return AppFrameworkAppCCMappingApiFp(this.configuration).getAppCCMapping(appId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete App CC Mapping
     * @summary Delete App CC Mapping
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeAppCCMapping(id: number, options?: RawAxiosRequestConfig) {
        return AppFrameworkAppCCMappingApiFp(this.configuration).removeAppCCMapping(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update App CC Mapping 
     * @summary Update App CC Mapping
     * @param {number} id 
     * @param {AppCCMappingRequest} appCCMappingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAppCCMapping(id: number, appCCMappingRequest: AppCCMappingRequest, options?: RawAxiosRequestConfig) {
        return AppFrameworkAppCCMappingApiFp(this.configuration).updateAppCCMapping(id, appCCMappingRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

