/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AsteriskSIPEntityBean } from '../models';
// @ts-ignore
import type { AsteriskSIPEntityRequest } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
/**
 * AsteriskSIPEntityApi - axios parameter creator
 */
export const AsteriskSIPEntityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Asterisk SIP Entity
         * @summary Add Asterisk SIP Entity
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAsteriskSIPEntity: async (asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'asteriskSIPEntityRequest' is not null or undefined
            assertParamExists('addAsteriskSIPEntity', 'asteriskSIPEntityRequest', asteriskSIPEntityRequest)
            const localVarPath = `/acs/asteriskSIPEntity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asteriskSIPEntityRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all Asterisk SIP Entity for voice resource
         * @summary Get all Asterisk SIP Entity for voice resource
         * @param {number} voiceResourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAsteriskSIPEntityByVoiceResource: async (voiceResourceId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'voiceResourceId' is not null or undefined
            assertParamExists('getAllAsteriskSIPEntityByVoiceResource', 'voiceResourceId', voiceResourceId)
            const localVarPath = `/acs/asteriskSIPEntity/getAllAsteriskSIPEntityByVoiceResource`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (voiceResourceId !== undefined) {
                localVarQueryParameter['voiceResourceId'] = voiceResourceId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify Asterisk SIP Entity
         * @summary Modify Asterisk SIP Entity
         * @param {number} entityId 
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyAsteriskSIPEntity: async (entityId: number, asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entityId' is not null or undefined
            assertParamExists('modifyAsteriskSIPEntity', 'entityId', entityId)
            // verify required parameter 'asteriskSIPEntityRequest' is not null or undefined
            assertParamExists('modifyAsteriskSIPEntity', 'asteriskSIPEntityRequest', asteriskSIPEntityRequest)
            const localVarPath = `/acs/asteriskSIPEntity/{entityId}`
                .replace('{entityId}', encodeURIComponent(String(entityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(asteriskSIPEntityRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Asterisk SIP Entity
         * @summary Remove Asterisk SIP Entity
         * @param {number} entityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAsteriskSIPEntity: async (entityId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'entityId' is not null or undefined
            assertParamExists('removeAsteriskSIPEntity', 'entityId', entityId)
            const localVarPath = `/acs/asteriskSIPEntity/{entityId}`
                .replace('{entityId}', encodeURIComponent(String(entityId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AsteriskSIPEntityApi - functional programming interface
 */
export const AsteriskSIPEntityApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AsteriskSIPEntityApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Asterisk SIP Entity
         * @summary Add Asterisk SIP Entity
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addAsteriskSIPEntity(asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsteriskSIPEntityBean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addAsteriskSIPEntity(asteriskSIPEntityRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsteriskSIPEntityApi.addAsteriskSIPEntity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all Asterisk SIP Entity for voice resource
         * @summary Get all Asterisk SIP Entity for voice resource
         * @param {number} voiceResourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAsteriskSIPEntityByVoiceResource(voiceResourceId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AsteriskSIPEntityBean>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAsteriskSIPEntityByVoiceResource(voiceResourceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsteriskSIPEntityApi.getAllAsteriskSIPEntityByVoiceResource']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify Asterisk SIP Entity
         * @summary Modify Asterisk SIP Entity
         * @param {number} entityId 
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyAsteriskSIPEntity(entityId: number, asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsteriskSIPEntityBean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyAsteriskSIPEntity(entityId, asteriskSIPEntityRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsteriskSIPEntityApi.modifyAsteriskSIPEntity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Asterisk SIP Entity
         * @summary Remove Asterisk SIP Entity
         * @param {number} entityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeAsteriskSIPEntity(entityId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeAsteriskSIPEntity(entityId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsteriskSIPEntityApi.removeAsteriskSIPEntity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AsteriskSIPEntityApi - factory interface
 */
export const AsteriskSIPEntityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AsteriskSIPEntityApiFp(configuration)
    return {
        /**
         * Add Asterisk SIP Entity
         * @summary Add Asterisk SIP Entity
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addAsteriskSIPEntity(asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig): AxiosPromise<AsteriskSIPEntityBean> {
            return localVarFp.addAsteriskSIPEntity(asteriskSIPEntityRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all Asterisk SIP Entity for voice resource
         * @summary Get all Asterisk SIP Entity for voice resource
         * @param {number} voiceResourceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAsteriskSIPEntityByVoiceResource(voiceResourceId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<AsteriskSIPEntityBean>> {
            return localVarFp.getAllAsteriskSIPEntityByVoiceResource(voiceResourceId, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify Asterisk SIP Entity
         * @summary Modify Asterisk SIP Entity
         * @param {number} entityId 
         * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyAsteriskSIPEntity(entityId: number, asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig): AxiosPromise<AsteriskSIPEntityBean> {
            return localVarFp.modifyAsteriskSIPEntity(entityId, asteriskSIPEntityRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Asterisk SIP Entity
         * @summary Remove Asterisk SIP Entity
         * @param {number} entityId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeAsteriskSIPEntity(entityId: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.removeAsteriskSIPEntity(entityId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AsteriskSIPEntityApi - object-oriented interface
 */
export class AsteriskSIPEntityApi extends BaseAPI {
    /**
     * Add Asterisk SIP Entity
     * @summary Add Asterisk SIP Entity
     * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addAsteriskSIPEntity(asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig) {
        return AsteriskSIPEntityApiFp(this.configuration).addAsteriskSIPEntity(asteriskSIPEntityRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all Asterisk SIP Entity for voice resource
     * @summary Get all Asterisk SIP Entity for voice resource
     * @param {number} voiceResourceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllAsteriskSIPEntityByVoiceResource(voiceResourceId: number, options?: RawAxiosRequestConfig) {
        return AsteriskSIPEntityApiFp(this.configuration).getAllAsteriskSIPEntityByVoiceResource(voiceResourceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify Asterisk SIP Entity
     * @summary Modify Asterisk SIP Entity
     * @param {number} entityId 
     * @param {AsteriskSIPEntityRequest} asteriskSIPEntityRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyAsteriskSIPEntity(entityId: number, asteriskSIPEntityRequest: AsteriskSIPEntityRequest, options?: RawAxiosRequestConfig) {
        return AsteriskSIPEntityApiFp(this.configuration).modifyAsteriskSIPEntity(entityId, asteriskSIPEntityRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Asterisk SIP Entity
     * @summary Remove Asterisk SIP Entity
     * @param {number} entityId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeAsteriskSIPEntity(entityId: number, options?: RawAxiosRequestConfig) {
        return AsteriskSIPEntityApiFp(this.configuration).removeAsteriskSIPEntity(entityId, options).then((request) => request(this.axios, this.basePath));
    }
}

