/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CallContext } from '../models';
// @ts-ignore
import type { CallContextRequest } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
/**
 * CallContextApi - axios parameter creator
 */
export const CallContextApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Call Context
         * @summary Add Call Context
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCallContext: async (callContextRequest: CallContextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callContextRequest' is not null or undefined
            assertParamExists('addCallContext', 'callContextRequest', callContextRequest)
            const localVarPath = `/cm/callContext`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(callContextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All Call Context
         * @summary Get All Call Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCallContext: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/cm/callContext/getAllCallContexts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify Call Context
         * @summary Modify Call Context
         * @param {number} callContextId 
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCallContext: async (callContextId: number, callContextRequest: CallContextRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callContextId' is not null or undefined
            assertParamExists('modifyCallContext', 'callContextId', callContextId)
            // verify required parameter 'callContextRequest' is not null or undefined
            assertParamExists('modifyCallContext', 'callContextRequest', callContextRequest)
            const localVarPath = `/cm/callContext/{callContextId}`
                .replace('{callContextId}', encodeURIComponent(String(callContextId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(callContextRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Call Context
         * @summary Remove Call Context
         * @param {number} callContextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCallContext: async (callContextId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'callContextId' is not null or undefined
            assertParamExists('removeCallContext', 'callContextId', callContextId)
            const localVarPath = `/cm/callContext/{callContextId}`
                .replace('{callContextId}', encodeURIComponent(String(callContextId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CallContextApi - functional programming interface
 */
export const CallContextApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CallContextApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Call Context
         * @summary Add Call Context
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCallContext(callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallContext>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addCallContext(callContextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallContextApi.addCallContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All Call Context
         * @summary Get All Call Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllCallContext(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CallContext>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCallContext(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallContextApi.getAllCallContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify Call Context
         * @summary Modify Call Context
         * @param {number} callContextId 
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyCallContext(callContextId: number, callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallContext>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyCallContext(callContextId, callContextRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallContextApi.modifyCallContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Call Context
         * @summary Remove Call Context
         * @param {number} callContextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeCallContext(callContextId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeCallContext(callContextId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallContextApi.removeCallContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CallContextApi - factory interface
 */
export const CallContextApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CallContextApiFp(configuration)
    return {
        /**
         * Add Call Context
         * @summary Add Call Context
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCallContext(callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallContext> {
            return localVarFp.addCallContext(callContextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All Call Context
         * @summary Get All Call Context
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCallContext(options?: RawAxiosRequestConfig): AxiosPromise<Array<CallContext>> {
            return localVarFp.getAllCallContext(options).then((request) => request(axios, basePath));
        },
        /**
         * Modify Call Context
         * @summary Modify Call Context
         * @param {number} callContextId 
         * @param {CallContextRequest} callContextRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCallContext(callContextId: number, callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallContext> {
            return localVarFp.modifyCallContext(callContextId, callContextRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Call Context
         * @summary Remove Call Context
         * @param {number} callContextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCallContext(callContextId: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.removeCallContext(callContextId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CallContextApi - object-oriented interface
 */
export class CallContextApi extends BaseAPI {
    /**
     * Add Call Context
     * @summary Add Call Context
     * @param {CallContextRequest} callContextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addCallContext(callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig) {
        return CallContextApiFp(this.configuration).addCallContext(callContextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All Call Context
     * @summary Get All Call Context
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllCallContext(options?: RawAxiosRequestConfig) {
        return CallContextApiFp(this.configuration).getAllCallContext(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify Call Context
     * @summary Modify Call Context
     * @param {number} callContextId 
     * @param {CallContextRequest} callContextRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyCallContext(callContextId: number, callContextRequest: CallContextRequest, options?: RawAxiosRequestConfig) {
        return CallContextApiFp(this.configuration).modifyCallContext(callContextId, callContextRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Call Context
     * @summary Remove Call Context
     * @param {number} callContextId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeCallContext(callContextId: number, options?: RawAxiosRequestConfig) {
        return CallContextApiFp(this.configuration).removeCallContext(callContextId, options).then((request) => request(this.axios, this.basePath));
    }
}

