/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddCustomerRepositoryMediaProcessMappingRequest } from '../models';
// @ts-ignore
import type { CustomerRepositoryMediaProcessMapping } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { ModifyCustomerRepositoryMediaProcessMappingRequest } from '../models';
/**
 * CentralCustomerRepositoryApi - axios parameter creator
 */
export const CentralCustomerRepositoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Customer Repository process mapping with Media process for Central Customer Repository
         * @summary Add Customer Repository Mapping
         * @param {AddCustomerRepositoryMediaProcessMappingRequest} addCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCustomerRepositoryMediaProcessMapping: async (addCustomerRepositoryMediaProcessMappingRequest: AddCustomerRepositoryMediaProcessMappingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'addCustomerRepositoryMediaProcessMappingRequest' is not null or undefined
            assertParamExists('addCustomerRepositoryMediaProcessMapping', 'addCustomerRepositoryMediaProcessMappingRequest', addCustomerRepositoryMediaProcessMappingRequest)
            const localVarPath = `/customermanagerconfig/customerRepositoryMediaProcessMapping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addCustomerRepositoryMediaProcessMappingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Customer Repository Mapping with given parameters
         * @summary Get Customer Repository Mapping
         * @param {number} [customerRepositoryMediaProcessMappingId] Unique Id of Customer Repository Media Process Mapping
         * @param {number} [centralCustomerRepositoryProcessId] Unique Id of Central Customer Repository Process
         * @param {number} [mediaProcessId] Unique Id of Media Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerRepositoryMediaProcessMapping: async (customerRepositoryMediaProcessMappingId?: number, centralCustomerRepositoryProcessId?: number, mediaProcessId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/customermanagerconfig/customerRepositoryMediaProcessMapping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (customerRepositoryMediaProcessMappingId !== undefined) {
                localVarQueryParameter['customerRepositoryMediaProcessMappingId'] = customerRepositoryMediaProcessMappingId;
            }

            if (centralCustomerRepositoryProcessId !== undefined) {
                localVarQueryParameter['centralCustomerRepositoryProcessId'] = centralCustomerRepositoryProcessId;
            }

            if (mediaProcessId !== undefined) {
                localVarQueryParameter['mediaProcessId'] = mediaProcessId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify Customer Repository Mapping with given parameters
         * @summary Modify Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {ModifyCustomerRepositoryMediaProcessMappingRequest} modifyCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCustomerRepositoryMediaProcessMapping: async (customerRepositoryMediaProcessMappingId: number, modifyCustomerRepositoryMediaProcessMappingRequest: ModifyCustomerRepositoryMediaProcessMappingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'customerRepositoryMediaProcessMappingId' is not null or undefined
            assertParamExists('modifyCustomerRepositoryMediaProcessMapping', 'customerRepositoryMediaProcessMappingId', customerRepositoryMediaProcessMappingId)
            // verify required parameter 'modifyCustomerRepositoryMediaProcessMappingRequest' is not null or undefined
            assertParamExists('modifyCustomerRepositoryMediaProcessMapping', 'modifyCustomerRepositoryMediaProcessMappingRequest', modifyCustomerRepositoryMediaProcessMappingRequest)
            const localVarPath = `/customermanagerconfig/customerRepositoryMediaProcessMapping/{customerRepositoryMediaProcessMappingId}`
                .replace('{customerRepositoryMediaProcessMappingId}', encodeURIComponent(String(customerRepositoryMediaProcessMappingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modifyCustomerRepositoryMediaProcessMappingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Customer Repository Mapping for the given Id
         * @summary Remove Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCustomerRepositoryMediaProcessMapping: async (customerRepositoryMediaProcessMappingId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'customerRepositoryMediaProcessMappingId' is not null or undefined
            assertParamExists('removeCustomerRepositoryMediaProcessMapping', 'customerRepositoryMediaProcessMappingId', customerRepositoryMediaProcessMappingId)
            const localVarPath = `/customermanagerconfig/customerRepositoryMediaProcessMapping/{customerRepositoryMediaProcessMappingId}`
                .replace('{customerRepositoryMediaProcessMappingId}', encodeURIComponent(String(customerRepositoryMediaProcessMappingId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CentralCustomerRepositoryApi - functional programming interface
 */
export const CentralCustomerRepositoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CentralCustomerRepositoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Customer Repository process mapping with Media process for Central Customer Repository
         * @summary Add Customer Repository Mapping
         * @param {AddCustomerRepositoryMediaProcessMappingRequest} addCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest: AddCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerRepositoryMediaProcessMapping>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CentralCustomerRepositoryApi.addCustomerRepositoryMediaProcessMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Customer Repository Mapping with given parameters
         * @summary Get Customer Repository Mapping
         * @param {number} [customerRepositoryMediaProcessMappingId] Unique Id of Customer Repository Media Process Mapping
         * @param {number} [centralCustomerRepositoryProcessId] Unique Id of Central Customer Repository Process
         * @param {number} [mediaProcessId] Unique Id of Media Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId?: number, centralCustomerRepositoryProcessId?: number, mediaProcessId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CustomerRepositoryMediaProcessMapping>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, centralCustomerRepositoryProcessId, mediaProcessId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CentralCustomerRepositoryApi.getCustomerRepositoryMediaProcessMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify Customer Repository Mapping with given parameters
         * @summary Modify Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {ModifyCustomerRepositoryMediaProcessMappingRequest} modifyCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, modifyCustomerRepositoryMediaProcessMappingRequest: ModifyCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CustomerRepositoryMediaProcessMapping>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, modifyCustomerRepositoryMediaProcessMappingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CentralCustomerRepositoryApi.modifyCustomerRepositoryMediaProcessMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Customer Repository Mapping for the given Id
         * @summary Remove Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CentralCustomerRepositoryApi.removeCustomerRepositoryMediaProcessMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CentralCustomerRepositoryApi - factory interface
 */
export const CentralCustomerRepositoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CentralCustomerRepositoryApiFp(configuration)
    return {
        /**
         * Add Customer Repository process mapping with Media process for Central Customer Repository
         * @summary Add Customer Repository Mapping
         * @param {AddCustomerRepositoryMediaProcessMappingRequest} addCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest: AddCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerRepositoryMediaProcessMapping> {
            return localVarFp.addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Customer Repository Mapping with given parameters
         * @summary Get Customer Repository Mapping
         * @param {number} [customerRepositoryMediaProcessMappingId] Unique Id of Customer Repository Media Process Mapping
         * @param {number} [centralCustomerRepositoryProcessId] Unique Id of Central Customer Repository Process
         * @param {number} [mediaProcessId] Unique Id of Media Process
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId?: number, centralCustomerRepositoryProcessId?: number, mediaProcessId?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CustomerRepositoryMediaProcessMapping>> {
            return localVarFp.getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, centralCustomerRepositoryProcessId, mediaProcessId, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify Customer Repository Mapping with given parameters
         * @summary Modify Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {ModifyCustomerRepositoryMediaProcessMappingRequest} modifyCustomerRepositoryMediaProcessMappingRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, modifyCustomerRepositoryMediaProcessMappingRequest: ModifyCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig): AxiosPromise<CustomerRepositoryMediaProcessMapping> {
            return localVarFp.modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, modifyCustomerRepositoryMediaProcessMappingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Customer Repository Mapping for the given Id
         * @summary Remove Customer Repository Mapping
         * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CentralCustomerRepositoryApi - object-oriented interface
 */
export class CentralCustomerRepositoryApi extends BaseAPI {
    /**
     * Add Customer Repository process mapping with Media process for Central Customer Repository
     * @summary Add Customer Repository Mapping
     * @param {AddCustomerRepositoryMediaProcessMappingRequest} addCustomerRepositoryMediaProcessMappingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest: AddCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig) {
        return CentralCustomerRepositoryApiFp(this.configuration).addCustomerRepositoryMediaProcessMapping(addCustomerRepositoryMediaProcessMappingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Customer Repository Mapping with given parameters
     * @summary Get Customer Repository Mapping
     * @param {number} [customerRepositoryMediaProcessMappingId] Unique Id of Customer Repository Media Process Mapping
     * @param {number} [centralCustomerRepositoryProcessId] Unique Id of Central Customer Repository Process
     * @param {number} [mediaProcessId] Unique Id of Media Process
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId?: number, centralCustomerRepositoryProcessId?: number, mediaProcessId?: number, options?: RawAxiosRequestConfig) {
        return CentralCustomerRepositoryApiFp(this.configuration).getCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, centralCustomerRepositoryProcessId, mediaProcessId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify Customer Repository Mapping with given parameters
     * @summary Modify Customer Repository Mapping
     * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
     * @param {ModifyCustomerRepositoryMediaProcessMappingRequest} modifyCustomerRepositoryMediaProcessMappingRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, modifyCustomerRepositoryMediaProcessMappingRequest: ModifyCustomerRepositoryMediaProcessMappingRequest, options?: RawAxiosRequestConfig) {
        return CentralCustomerRepositoryApiFp(this.configuration).modifyCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, modifyCustomerRepositoryMediaProcessMappingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Customer Repository Mapping for the given Id
     * @summary Remove Customer Repository Mapping
     * @param {number} customerRepositoryMediaProcessMappingId Unique Id of Customer Repository Media Process Mapping
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId: number, options?: RawAxiosRequestConfig) {
        return CentralCustomerRepositoryApiFp(this.configuration).removeCustomerRepositoryMediaProcessMapping(customerRepositoryMediaProcessMappingId, options).then((request) => request(this.axios, this.basePath));
    }
}

