/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AssignCallContextsToContactCenterRequest } from '../models';
// @ts-ignore
import type { ContactCenterCallContext } from '../models';
// @ts-ignore
import type { ContactCenterCallContextDetailOutputRequest } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { ModifyContactCenterCallContextsRequest } from '../models';
/**
 * ContactCenterCallContextApi - axios parameter creator
 */
export const ContactCenterCallContextApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Assign Call Contexts To the given Contact Center
         * @summary Assign Call Contexts To Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {AssignCallContextsToContactCenterRequest} assignCallContextsToContactCenterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCallContextsToContactCenter: async (contactCenterId: number, assignCallContextsToContactCenterRequest: AssignCallContextsToContactCenterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('assignCallContextsToContactCenter', 'contactCenterId', contactCenterId)
            // verify required parameter 'assignCallContextsToContactCenterRequest' is not null or undefined
            assertParamExists('assignCallContextsToContactCenter', 'assignCallContextsToContactCenterRequest', assignCallContextsToContactCenterRequest)
            const localVarPath = `/hierarchyconfig/contactCenter/{contactCenterId}/assignCallContextsToContactCenter`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignCallContextsToContactCenterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all Contact Center Call Contexts for the given Contact Center
         * @summary Get Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContactCenterCallContext: async (contactCenterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllContactCenterCallContext', 'contactCenterId', contactCenterId)
            const localVarPath = `/hierarchyconfig/contactCenter/{contactCenterId}/getAllContactCenterCallContext`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all Contact Center Call Contexts  Details for the given Contact Center
         * @summary Get Contact Center Call Contexts Details
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContactCenterCallContextDetails: async (contactCenterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllContactCenterCallContextDetails', 'contactCenterId', contactCenterId)
            const localVarPath = `/hierarchyconfig/contactCenter/{contactCenterId}/getAllContactCenterCallContextDetails`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Modify Contact Center Call Contexts for the given Contact Center
         * @summary Modify Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {ModifyContactCenterCallContextsRequest} modifyContactCenterCallContextsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyContactCenterCallContexts: async (contactCenterId: number, modifyContactCenterCallContextsRequest: ModifyContactCenterCallContextsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('modifyContactCenterCallContexts', 'contactCenterId', contactCenterId)
            // verify required parameter 'modifyContactCenterCallContextsRequest' is not null or undefined
            assertParamExists('modifyContactCenterCallContexts', 'modifyContactCenterCallContextsRequest', modifyContactCenterCallContextsRequest)
            const localVarPath = `/hierarchyconfig/contactCenter/{contactCenterId}/modifyContactCenterCallContexts`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modifyContactCenterCallContextsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unassign Call Contexts From the given Contact Center
         * @summary Unassign Call Contexts From Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {Array<number>} callContextIds List of Call Context Ids to be Unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignCallContextsFromContactCenter: async (contactCenterId: number, callContextIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('unassignCallContextsFromContactCenter', 'contactCenterId', contactCenterId)
            // verify required parameter 'callContextIds' is not null or undefined
            assertParamExists('unassignCallContextsFromContactCenter', 'callContextIds', callContextIds)
            const localVarPath = `/hierarchyconfig/contactCenter/{contactCenterId}/unassignCallContextsFromContactCenter`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (callContextIds) {
                localVarQueryParameter['callContextIds'] = callContextIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContactCenterCallContextApi - functional programming interface
 */
export const ContactCenterCallContextApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContactCenterCallContextApiAxiosParamCreator(configuration)
    return {
        /**
         * Assign Call Contexts To the given Contact Center
         * @summary Assign Call Contexts To Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {AssignCallContextsToContactCenterRequest} assignCallContextsToContactCenterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignCallContextsToContactCenter(contactCenterId: number, assignCallContextsToContactCenterRequest: AssignCallContextsToContactCenterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContactCenterCallContext>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignCallContextsToContactCenter(contactCenterId, assignCallContextsToContactCenterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactCenterCallContextApi.assignCallContextsToContactCenter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all Contact Center Call Contexts for the given Contact Center
         * @summary Get Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllContactCenterCallContext(contactCenterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContactCenterCallContext>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllContactCenterCallContext(contactCenterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactCenterCallContextApi.getAllContactCenterCallContext']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all Contact Center Call Contexts  Details for the given Contact Center
         * @summary Get Contact Center Call Contexts Details
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllContactCenterCallContextDetails(contactCenterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContactCenterCallContextDetailOutputRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllContactCenterCallContextDetails(contactCenterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactCenterCallContextApi.getAllContactCenterCallContextDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Modify Contact Center Call Contexts for the given Contact Center
         * @summary Modify Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {ModifyContactCenterCallContextsRequest} modifyContactCenterCallContextsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyContactCenterCallContexts(contactCenterId: number, modifyContactCenterCallContextsRequest: ModifyContactCenterCallContextsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContactCenterCallContext>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyContactCenterCallContexts(contactCenterId, modifyContactCenterCallContextsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactCenterCallContextApi.modifyContactCenterCallContexts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unassign Call Contexts From the given Contact Center
         * @summary Unassign Call Contexts From Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {Array<number>} callContextIds List of Call Context Ids to be Unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unassignCallContextsFromContactCenter(contactCenterId: number, callContextIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unassignCallContextsFromContactCenter(contactCenterId, callContextIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContactCenterCallContextApi.unassignCallContextsFromContactCenter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContactCenterCallContextApi - factory interface
 */
export const ContactCenterCallContextApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContactCenterCallContextApiFp(configuration)
    return {
        /**
         * Assign Call Contexts To the given Contact Center
         * @summary Assign Call Contexts To Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {AssignCallContextsToContactCenterRequest} assignCallContextsToContactCenterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCallContextsToContactCenter(contactCenterId: number, assignCallContextsToContactCenterRequest: AssignCallContextsToContactCenterRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactCenterCallContext>> {
            return localVarFp.assignCallContextsToContactCenter(contactCenterId, assignCallContextsToContactCenterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all Contact Center Call Contexts for the given Contact Center
         * @summary Get Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContactCenterCallContext(contactCenterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactCenterCallContext>> {
            return localVarFp.getAllContactCenterCallContext(contactCenterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all Contact Center Call Contexts  Details for the given Contact Center
         * @summary Get Contact Center Call Contexts Details
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllContactCenterCallContextDetails(contactCenterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactCenterCallContextDetailOutputRequest>> {
            return localVarFp.getAllContactCenterCallContextDetails(contactCenterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Modify Contact Center Call Contexts for the given Contact Center
         * @summary Modify Contact Center Call Contexts
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {ModifyContactCenterCallContextsRequest} modifyContactCenterCallContextsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyContactCenterCallContexts(contactCenterId: number, modifyContactCenterCallContextsRequest: ModifyContactCenterCallContextsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContactCenterCallContext>> {
            return localVarFp.modifyContactCenterCallContexts(contactCenterId, modifyContactCenterCallContextsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unassign Call Contexts From the given Contact Center
         * @summary Unassign Call Contexts From Contact Center
         * @param {number} contactCenterId Unique Id of Contact Center
         * @param {Array<number>} callContextIds List of Call Context Ids to be Unassigned
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignCallContextsFromContactCenter(contactCenterId: number, callContextIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unassignCallContextsFromContactCenter(contactCenterId, callContextIds, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContactCenterCallContextApi - object-oriented interface
 */
export class ContactCenterCallContextApi extends BaseAPI {
    /**
     * Assign Call Contexts To the given Contact Center
     * @summary Assign Call Contexts To Contact Center
     * @param {number} contactCenterId Unique Id of Contact Center
     * @param {AssignCallContextsToContactCenterRequest} assignCallContextsToContactCenterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignCallContextsToContactCenter(contactCenterId: number, assignCallContextsToContactCenterRequest: AssignCallContextsToContactCenterRequest, options?: RawAxiosRequestConfig) {
        return ContactCenterCallContextApiFp(this.configuration).assignCallContextsToContactCenter(contactCenterId, assignCallContextsToContactCenterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all Contact Center Call Contexts for the given Contact Center
     * @summary Get Contact Center Call Contexts
     * @param {number} contactCenterId Unique Id of Contact Center
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllContactCenterCallContext(contactCenterId: number, options?: RawAxiosRequestConfig) {
        return ContactCenterCallContextApiFp(this.configuration).getAllContactCenterCallContext(contactCenterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all Contact Center Call Contexts  Details for the given Contact Center
     * @summary Get Contact Center Call Contexts Details
     * @param {number} contactCenterId Unique Id of Contact Center
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllContactCenterCallContextDetails(contactCenterId: number, options?: RawAxiosRequestConfig) {
        return ContactCenterCallContextApiFp(this.configuration).getAllContactCenterCallContextDetails(contactCenterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Modify Contact Center Call Contexts for the given Contact Center
     * @summary Modify Contact Center Call Contexts
     * @param {number} contactCenterId Unique Id of Contact Center
     * @param {ModifyContactCenterCallContextsRequest} modifyContactCenterCallContextsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyContactCenterCallContexts(contactCenterId: number, modifyContactCenterCallContextsRequest: ModifyContactCenterCallContextsRequest, options?: RawAxiosRequestConfig) {
        return ContactCenterCallContextApiFp(this.configuration).modifyContactCenterCallContexts(contactCenterId, modifyContactCenterCallContextsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unassign Call Contexts From the given Contact Center
     * @summary Unassign Call Contexts From Contact Center
     * @param {number} contactCenterId Unique Id of Contact Center
     * @param {Array<number>} callContextIds List of Call Context Ids to be Unassigned
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unassignCallContextsFromContactCenter(contactCenterId: number, callContextIds: Array<number>, options?: RawAxiosRequestConfig) {
        return ContactCenterCallContextApiFp(this.configuration).unassignCallContextsFromContactCenter(contactCenterId, callContextIds, options).then((request) => request(this.axios, this.basePath));
    }
}

