/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResponse } from '../models';
// @ts-ignore
import type { CreateDIDRequest } from '../models';
// @ts-ignore
import type { CreateDidInDcRequest } from '../models';
// @ts-ignore
import type { DIDConfiguration } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { GetAllDIDResponse } from '../models';
// @ts-ignore
import type { ModifyDIDRequest } from '../models';
// @ts-ignore
import type { ModifyDidInDcRequest } from '../models';
/**
 * DIDApi - axios parameter creator
 */
export const DIDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This api will create DIDs to DC mapping for a CC
         * @summary Create DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {CreateDidInDcRequest} createDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDIDsInDC: async (ccId: number, dataCenterId: string, createDidInDcRequest: CreateDidInDcRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('createDIDsInDC', 'ccId', ccId)
            // verify required parameter 'dataCenterId' is not null or undefined
            assertParamExists('createDIDsInDC', 'dataCenterId', dataCenterId)
            // verify required parameter 'createDidInDcRequest' is not null or undefined
            assertParamExists('createDIDsInDC', 'createDidInDcRequest', createDidInDcRequest)
            const localVarPath = `/didConfiguration/cc-list/{ccId}/data-center/{dataCenterId}/did`
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{dataCenterId}', encodeURIComponent(String(dataCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDidInDcRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * create DID in DID Group
         * @summary create DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {CreateDIDRequest} createDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDIDsInDIDGroup: async (campaignId: number, processId: number, ccId: number, didGroupId: number, createDIDRequest: CreateDIDRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignId' is not null or undefined
            assertParamExists('createDIDsInDIDGroup', 'campaignId', campaignId)
            // verify required parameter 'processId' is not null or undefined
            assertParamExists('createDIDsInDIDGroup', 'processId', processId)
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('createDIDsInDIDGroup', 'ccId', ccId)
            // verify required parameter 'didGroupId' is not null or undefined
            assertParamExists('createDIDsInDIDGroup', 'didGroupId', didGroupId)
            // verify required parameter 'createDIDRequest' is not null or undefined
            assertParamExists('createDIDsInDIDGroup', 'createDIDRequest', createDIDRequest)
            const localVarPath = `/didConfiguration/createDIDsInDIDGroup/campaignId/{campaignId}/processId/{processId}/ccId/{ccId}/didGroupId/{didGroupId}`
                .replace('{campaignId}', encodeURIComponent(String(campaignId)))
                .replace('{processId}', encodeURIComponent(String(processId)))
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{didGroupId}', encodeURIComponent(String(didGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDIDRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This api will remove the particular configured DID for a CC and data center
         * @summary Delete DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDID: async (ccId: number, dataCenterId: string, did: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('deleteDID', 'ccId', ccId)
            // verify required parameter 'dataCenterId' is not null or undefined
            assertParamExists('deleteDID', 'dataCenterId', dataCenterId)
            // verify required parameter 'did' is not null or undefined
            assertParamExists('deleteDID', 'did', did)
            const localVarPath = `/didConfiguration/cc-list/{ccId}/data-center/{dataCenterId}/did/{did}`
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{dataCenterId}', encodeURIComponent(String(dataCenterId)))
                .replace('{did}', encodeURIComponent(String(did)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * delete DID from DID Group
         * @summary delete DID from DID Group
         * @param {Array<number>} didList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDIDsFromDIDGroup: async (didList: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'didList' is not null or undefined
            assertParamExists('deleteDIDsFromDIDGroup', 'didList', didList)
            const localVarPath = `/didConfiguration/deleteDIDsFromDIDGroup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (didList) {
                localVarQueryParameter['didList'] = didList;
            }

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This API will return all the configured DIDs for a CC and data center
         * @summary Get all DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDIDs: async (ccId: number, dataCenterId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('getAllDIDs', 'ccId', ccId)
            // verify required parameter 'dataCenterId' is not null or undefined
            assertParamExists('getAllDIDs', 'dataCenterId', dataCenterId)
            const localVarPath = `/didConfiguration/cc-list/{ccId}/data-center/{dataCenterId}/did`
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{dataCenterId}', encodeURIComponent(String(dataCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All DIDs assigned to a group
         * @summary Get All DIDs assigned to a group
         * @param {number} didGroupId 
         * @param {number} page 
         * @param {number} limit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDIDsInDIDGroup: async (didGroupId: number, page: number, limit: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'didGroupId' is not null or undefined
            assertParamExists('getAllDIDsInDIDGroup', 'didGroupId', didGroupId)
            // verify required parameter 'page' is not null or undefined
            assertParamExists('getAllDIDsInDIDGroup', 'page', page)
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('getAllDIDsInDIDGroup', 'limit', limit)
            const localVarPath = `/didConfiguration/did/didGroupId/{didGroupId}`
                .replace('{didGroupId}', encodeURIComponent(String(didGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This API will return the configured DID for a CC and data center
         * @summary Get DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDID: async (ccId: number, dataCenterId: string, did: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('getDID', 'ccId', ccId)
            // verify required parameter 'dataCenterId' is not null or undefined
            assertParamExists('getDID', 'dataCenterId', dataCenterId)
            // verify required parameter 'did' is not null or undefined
            assertParamExists('getDID', 'did', did)
            const localVarPath = `/didConfiguration/cc-list/{ccId}/data-center/{dataCenterId}/did/{did}`
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{dataCenterId}', encodeURIComponent(String(dataCenterId)))
                .replace('{did}', encodeURIComponent(String(did)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This api will modify DID to DC mapping
         * @summary modify DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {ModifyDidInDcRequest} modifyDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyDIDsInDC: async (ccId: number, dataCenterId: string, did: string, modifyDidInDcRequest: ModifyDidInDcRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('modifyDIDsInDC', 'ccId', ccId)
            // verify required parameter 'dataCenterId' is not null or undefined
            assertParamExists('modifyDIDsInDC', 'dataCenterId', dataCenterId)
            // verify required parameter 'did' is not null or undefined
            assertParamExists('modifyDIDsInDC', 'did', did)
            // verify required parameter 'modifyDidInDcRequest' is not null or undefined
            assertParamExists('modifyDIDsInDC', 'modifyDidInDcRequest', modifyDidInDcRequest)
            const localVarPath = `/didConfiguration/cc-list/{ccId}/data-center/{dataCenterId}/did/{did}`
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{dataCenterId}', encodeURIComponent(String(dataCenterId)))
                .replace('{did}', encodeURIComponent(String(did)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modifyDidInDcRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * modify DID in DID Group
         * @summary modify DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {ModifyDIDRequest} modifyDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyDIDsInDIDGroup: async (campaignId: number, processId: number, ccId: number, didGroupId: number, modifyDIDRequest: ModifyDIDRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignId' is not null or undefined
            assertParamExists('modifyDIDsInDIDGroup', 'campaignId', campaignId)
            // verify required parameter 'processId' is not null or undefined
            assertParamExists('modifyDIDsInDIDGroup', 'processId', processId)
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('modifyDIDsInDIDGroup', 'ccId', ccId)
            // verify required parameter 'didGroupId' is not null or undefined
            assertParamExists('modifyDIDsInDIDGroup', 'didGroupId', didGroupId)
            // verify required parameter 'modifyDIDRequest' is not null or undefined
            assertParamExists('modifyDIDsInDIDGroup', 'modifyDIDRequest', modifyDIDRequest)
            const localVarPath = `/didConfiguration/modifyDIDsInDIDGroup/campaignId/{campaignId}/processId/{processId}/ccId/{ccId}/didGroupId/{didGroupId}`
                .replace('{campaignId}', encodeURIComponent(String(campaignId)))
                .replace('{processId}', encodeURIComponent(String(processId)))
                .replace('{ccId}', encodeURIComponent(String(ccId)))
                .replace('{didGroupId}', encodeURIComponent(String(didGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(modifyDIDRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DIDApi - functional programming interface
 */
export const DIDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DIDApiAxiosParamCreator(configuration)
    return {
        /**
         * This api will create DIDs to DC mapping for a CC
         * @summary Create DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {CreateDidInDcRequest} createDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDIDsInDC(ccId: number, dataCenterId: string, createDidInDcRequest: CreateDidInDcRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDIDsInDC(ccId, dataCenterId, createDidInDcRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.createDIDsInDC']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * create DID in DID Group
         * @summary create DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {CreateDIDRequest} createDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, createDIDRequest: CreateDIDRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DIDConfiguration>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, createDIDRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.createDIDsInDIDGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This api will remove the particular configured DID for a CC and data center
         * @summary Delete DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDID(ccId, dataCenterId, did, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.deleteDID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * delete DID from DID Group
         * @summary delete DID from DID Group
         * @param {Array<number>} didList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDIDsFromDIDGroup(didList: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DIDConfiguration>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDIDsFromDIDGroup(didList, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.deleteDIDsFromDIDGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API will return all the configured DIDs for a CC and data center
         * @summary Get all DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDIDs(ccId: number, dataCenterId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDIDs(ccId, dataCenterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.getAllDIDs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All DIDs assigned to a group
         * @summary Get All DIDs assigned to a group
         * @param {number} didGroupId 
         * @param {number} page 
         * @param {number} limit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDIDsInDIDGroup(didGroupId: number, page: number, limit: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAllDIDResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDIDsInDIDGroup(didGroupId, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.getAllDIDsInDIDGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API will return the configured DID for a CC and data center
         * @summary Get DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDID(ccId, dataCenterId, did, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.getDID']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This api will modify DID to DC mapping
         * @summary modify DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {ModifyDidInDcRequest} modifyDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyDIDsInDC(ccId: number, dataCenterId: string, did: string, modifyDidInDcRequest: ModifyDidInDcRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyDIDsInDC(ccId, dataCenterId, did, modifyDidInDcRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.modifyDIDsInDC']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * modify DID in DID Group
         * @summary modify DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {ModifyDIDRequest} modifyDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, modifyDIDRequest: ModifyDIDRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DIDConfiguration>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, modifyDIDRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DIDApi.modifyDIDsInDIDGroup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DIDApi - factory interface
 */
export const DIDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DIDApiFp(configuration)
    return {
        /**
         * This api will create DIDs to DC mapping for a CC
         * @summary Create DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {CreateDidInDcRequest} createDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDIDsInDC(ccId: number, dataCenterId: string, createDidInDcRequest: CreateDidInDcRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.createDIDsInDC(ccId, dataCenterId, createDidInDcRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * create DID in DID Group
         * @summary create DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {CreateDIDRequest} createDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, createDIDRequest: CreateDIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<DIDConfiguration>> {
            return localVarFp.createDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, createDIDRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * This api will remove the particular configured DID for a CC and data center
         * @summary Delete DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.deleteDID(ccId, dataCenterId, did, options).then((request) => request(axios, basePath));
        },
        /**
         * delete DID from DID Group
         * @summary delete DID from DID Group
         * @param {Array<number>} didList 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDIDsFromDIDGroup(didList: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<Array<DIDConfiguration>> {
            return localVarFp.deleteDIDsFromDIDGroup(didList, options).then((request) => request(axios, basePath));
        },
        /**
         * This API will return all the configured DIDs for a CC and data center
         * @summary Get all DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDIDs(ccId: number, dataCenterId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.getAllDIDs(ccId, dataCenterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All DIDs assigned to a group
         * @summary Get All DIDs assigned to a group
         * @param {number} didGroupId 
         * @param {number} page 
         * @param {number} limit 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDIDsInDIDGroup(didGroupId: number, page: number, limit: number, options?: RawAxiosRequestConfig): AxiosPromise<GetAllDIDResponse> {
            return localVarFp.getAllDIDsInDIDGroup(didGroupId, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * This API will return the configured DID for a CC and data center
         * @summary Get DID for a DC and CC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.getDID(ccId, dataCenterId, did, options).then((request) => request(axios, basePath));
        },
        /**
         * This api will modify DID to DC mapping
         * @summary modify DID in DC
         * @param {number} ccId 
         * @param {string} dataCenterId 
         * @param {string} did 
         * @param {ModifyDidInDcRequest} modifyDidInDcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyDIDsInDC(ccId: number, dataCenterId: string, did: string, modifyDidInDcRequest: ModifyDidInDcRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.modifyDIDsInDC(ccId, dataCenterId, did, modifyDidInDcRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * modify DID in DID Group
         * @summary modify DID in DID Group
         * @param {number} campaignId 
         * @param {number} processId 
         * @param {number} ccId 
         * @param {number} didGroupId 
         * @param {ModifyDIDRequest} modifyDIDRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, modifyDIDRequest: ModifyDIDRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<DIDConfiguration>> {
            return localVarFp.modifyDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, modifyDIDRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DIDApi - object-oriented interface
 */
export class DIDApi extends BaseAPI {
    /**
     * This api will create DIDs to DC mapping for a CC
     * @summary Create DID in DC
     * @param {number} ccId 
     * @param {string} dataCenterId 
     * @param {CreateDidInDcRequest} createDidInDcRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDIDsInDC(ccId: number, dataCenterId: string, createDidInDcRequest: CreateDidInDcRequest, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).createDIDsInDC(ccId, dataCenterId, createDidInDcRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * create DID in DID Group
     * @summary create DID in DID Group
     * @param {number} campaignId 
     * @param {number} processId 
     * @param {number} ccId 
     * @param {number} didGroupId 
     * @param {CreateDIDRequest} createDIDRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, createDIDRequest: CreateDIDRequest, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).createDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, createDIDRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This api will remove the particular configured DID for a CC and data center
     * @summary Delete DID for a DC and CC
     * @param {number} ccId 
     * @param {string} dataCenterId 
     * @param {string} did 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).deleteDID(ccId, dataCenterId, did, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * delete DID from DID Group
     * @summary delete DID from DID Group
     * @param {Array<number>} didList 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDIDsFromDIDGroup(didList: Array<number>, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).deleteDIDsFromDIDGroup(didList, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API will return all the configured DIDs for a CC and data center
     * @summary Get all DID for a DC and CC
     * @param {number} ccId 
     * @param {string} dataCenterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllDIDs(ccId: number, dataCenterId: string, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).getAllDIDs(ccId, dataCenterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All DIDs assigned to a group
     * @summary Get All DIDs assigned to a group
     * @param {number} didGroupId 
     * @param {number} page 
     * @param {number} limit 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllDIDsInDIDGroup(didGroupId: number, page: number, limit: number, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).getAllDIDsInDIDGroup(didGroupId, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API will return the configured DID for a CC and data center
     * @summary Get DID for a DC and CC
     * @param {number} ccId 
     * @param {string} dataCenterId 
     * @param {string} did 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDID(ccId: number, dataCenterId: string, did: string, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).getDID(ccId, dataCenterId, did, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This api will modify DID to DC mapping
     * @summary modify DID in DC
     * @param {number} ccId 
     * @param {string} dataCenterId 
     * @param {string} did 
     * @param {ModifyDidInDcRequest} modifyDidInDcRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyDIDsInDC(ccId: number, dataCenterId: string, did: string, modifyDidInDcRequest: ModifyDidInDcRequest, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).modifyDIDsInDC(ccId, dataCenterId, did, modifyDidInDcRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * modify DID in DID Group
     * @summary modify DID in DID Group
     * @param {number} campaignId 
     * @param {number} processId 
     * @param {number} ccId 
     * @param {number} didGroupId 
     * @param {ModifyDIDRequest} modifyDIDRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyDIDsInDIDGroup(campaignId: number, processId: number, ccId: number, didGroupId: number, modifyDIDRequest: ModifyDIDRequest, options?: RawAxiosRequestConfig) {
        return DIDApiFp(this.configuration).modifyDIDsInDIDGroup(campaignId, processId, ccId, didGroupId, modifyDIDRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

