/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AssignCallContextsForCustomerAndAgentRequest } from '../models';
// @ts-ignore
import type { AssignVoiceResourcesToCampaignRequest } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { FailoverCampaign } from '../models';
// @ts-ignore
import type { UnassignCallContextsForCustomerAndAgentRequest } from '../models';
/**
 * FailoverPolicyApi - axios parameter creator
 */
export const FailoverPolicyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Assign call context for customer and agent
         * @summary Assign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignCallContextsForCustomerAndAgentRequest} assignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCallContextsForCustomerAndAgent: async (failoverCampaignId: number, assignCallContextsForCustomerAndAgentRequest: AssignCallContextsForCustomerAndAgentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'failoverCampaignId' is not null or undefined
            assertParamExists('assignCallContextsForCustomerAndAgent', 'failoverCampaignId', failoverCampaignId)
            // verify required parameter 'assignCallContextsForCustomerAndAgentRequest' is not null or undefined
            assertParamExists('assignCallContextsForCustomerAndAgent', 'assignCallContextsForCustomerAndAgentRequest', assignCallContextsForCustomerAndAgentRequest)
            const localVarPath = `/failoverconfig/failoverCampaign/{failoverCampaignId}/assignCallContextsForCustomerAndAgent`
                .replace('{failoverCampaignId}', encodeURIComponent(String(failoverCampaignId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignCallContextsForCustomerAndAgentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Assign voice resources to the failover campaign id
         * @summary Assign VR to failover campaign
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignVoiceResourcesToCampaignRequest} assignVoiceResourcesToCampaignRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignVoiceResourcesToCampaign: async (failoverCampaignId: number, assignVoiceResourcesToCampaignRequest: AssignVoiceResourcesToCampaignRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'failoverCampaignId' is not null or undefined
            assertParamExists('assignVoiceResourcesToCampaign', 'failoverCampaignId', failoverCampaignId)
            // verify required parameter 'assignVoiceResourcesToCampaignRequest' is not null or undefined
            assertParamExists('assignVoiceResourcesToCampaign', 'assignVoiceResourcesToCampaignRequest', assignVoiceResourcesToCampaignRequest)
            const localVarPath = `/failoverconfig/failoverCampaign/{failoverCampaignId}/assignVoiceResources`
                .replace('{failoverCampaignId}', encodeURIComponent(String(failoverCampaignId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignVoiceResourcesToCampaignRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unassign call context for customer and agent
         * @summary Unassign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {UnassignCallContextsForCustomerAndAgentRequest} unassignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignCallContextsForCustomerAndAgent: async (failoverCampaignId: number, unassignCallContextsForCustomerAndAgentRequest: UnassignCallContextsForCustomerAndAgentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'failoverCampaignId' is not null or undefined
            assertParamExists('unassignCallContextsForCustomerAndAgent', 'failoverCampaignId', failoverCampaignId)
            // verify required parameter 'unassignCallContextsForCustomerAndAgentRequest' is not null or undefined
            assertParamExists('unassignCallContextsForCustomerAndAgent', 'unassignCallContextsForCustomerAndAgentRequest', unassignCallContextsForCustomerAndAgentRequest)
            const localVarPath = `/failoverconfig/failoverCampaign/{failoverCampaignId}/unassignCallContextsForCustomerAndAgent`
                .replace('{failoverCampaignId}', encodeURIComponent(String(failoverCampaignId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(unassignCallContextsForCustomerAndAgentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FailoverPolicyApi - functional programming interface
 */
export const FailoverPolicyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FailoverPolicyApiAxiosParamCreator(configuration)
    return {
        /**
         * Assign call context for customer and agent
         * @summary Assign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignCallContextsForCustomerAndAgentRequest} assignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignCallContextsForCustomerAndAgent(failoverCampaignId: number, assignCallContextsForCustomerAndAgentRequest: AssignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FailoverCampaign>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignCallContextsForCustomerAndAgent(failoverCampaignId, assignCallContextsForCustomerAndAgentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FailoverPolicyApi.assignCallContextsForCustomerAndAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Assign voice resources to the failover campaign id
         * @summary Assign VR to failover campaign
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignVoiceResourcesToCampaignRequest} assignVoiceResourcesToCampaignRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignVoiceResourcesToCampaign(failoverCampaignId: number, assignVoiceResourcesToCampaignRequest: AssignVoiceResourcesToCampaignRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FailoverCampaign>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignVoiceResourcesToCampaign(failoverCampaignId, assignVoiceResourcesToCampaignRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FailoverPolicyApi.assignVoiceResourcesToCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unassign call context for customer and agent
         * @summary Unassign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {UnassignCallContextsForCustomerAndAgentRequest} unassignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unassignCallContextsForCustomerAndAgent(failoverCampaignId: number, unassignCallContextsForCustomerAndAgentRequest: UnassignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FailoverCampaign>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unassignCallContextsForCustomerAndAgent(failoverCampaignId, unassignCallContextsForCustomerAndAgentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FailoverPolicyApi.unassignCallContextsForCustomerAndAgent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FailoverPolicyApi - factory interface
 */
export const FailoverPolicyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FailoverPolicyApiFp(configuration)
    return {
        /**
         * Assign call context for customer and agent
         * @summary Assign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignCallContextsForCustomerAndAgentRequest} assignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignCallContextsForCustomerAndAgent(failoverCampaignId: number, assignCallContextsForCustomerAndAgentRequest: AssignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig): AxiosPromise<FailoverCampaign> {
            return localVarFp.assignCallContextsForCustomerAndAgent(failoverCampaignId, assignCallContextsForCustomerAndAgentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Assign voice resources to the failover campaign id
         * @summary Assign VR to failover campaign
         * @param {number} failoverCampaignId Failover campaign id
         * @param {AssignVoiceResourcesToCampaignRequest} assignVoiceResourcesToCampaignRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignVoiceResourcesToCampaign(failoverCampaignId: number, assignVoiceResourcesToCampaignRequest: AssignVoiceResourcesToCampaignRequest, options?: RawAxiosRequestConfig): AxiosPromise<FailoverCampaign> {
            return localVarFp.assignVoiceResourcesToCampaign(failoverCampaignId, assignVoiceResourcesToCampaignRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Unassign call context for customer and agent
         * @summary Unassign call context for customer and agent
         * @param {number} failoverCampaignId Failover campaign id
         * @param {UnassignCallContextsForCustomerAndAgentRequest} unassignCallContextsForCustomerAndAgentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignCallContextsForCustomerAndAgent(failoverCampaignId: number, unassignCallContextsForCustomerAndAgentRequest: UnassignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig): AxiosPromise<FailoverCampaign> {
            return localVarFp.unassignCallContextsForCustomerAndAgent(failoverCampaignId, unassignCallContextsForCustomerAndAgentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FailoverPolicyApi - object-oriented interface
 */
export class FailoverPolicyApi extends BaseAPI {
    /**
     * Assign call context for customer and agent
     * @summary Assign call context for customer and agent
     * @param {number} failoverCampaignId Failover campaign id
     * @param {AssignCallContextsForCustomerAndAgentRequest} assignCallContextsForCustomerAndAgentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignCallContextsForCustomerAndAgent(failoverCampaignId: number, assignCallContextsForCustomerAndAgentRequest: AssignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig) {
        return FailoverPolicyApiFp(this.configuration).assignCallContextsForCustomerAndAgent(failoverCampaignId, assignCallContextsForCustomerAndAgentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Assign voice resources to the failover campaign id
     * @summary Assign VR to failover campaign
     * @param {number} failoverCampaignId Failover campaign id
     * @param {AssignVoiceResourcesToCampaignRequest} assignVoiceResourcesToCampaignRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignVoiceResourcesToCampaign(failoverCampaignId: number, assignVoiceResourcesToCampaignRequest: AssignVoiceResourcesToCampaignRequest, options?: RawAxiosRequestConfig) {
        return FailoverPolicyApiFp(this.configuration).assignVoiceResourcesToCampaign(failoverCampaignId, assignVoiceResourcesToCampaignRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unassign call context for customer and agent
     * @summary Unassign call context for customer and agent
     * @param {number} failoverCampaignId Failover campaign id
     * @param {UnassignCallContextsForCustomerAndAgentRequest} unassignCallContextsForCustomerAndAgentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unassignCallContextsForCustomerAndAgent(failoverCampaignId: number, unassignCallContextsForCustomerAndAgentRequest: UnassignCallContextsForCustomerAndAgentRequest, options?: RawAxiosRequestConfig) {
        return FailoverPolicyApiFp(this.configuration).unassignCallContextsForCustomerAndAgent(failoverCampaignId, unassignCallContextsForCustomerAndAgentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

