/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { LocalIVR } from '../models';
// @ts-ignore
import type { LocalIVRRequest } from '../models';
/**
 * LocalIVRApi - axios parameter creator
 */
export const LocalIVRApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Local IVR
         * @summary Add Local IVR
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLocalIVRForCampaign: async (localIVRRequest: LocalIVRRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'localIVRRequest' is not null or undefined
            assertParamExists('addLocalIVRForCampaign', 'localIVRRequest', localIVRRequest)
            const localVarPath = `/voice/localIVR`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(localIVRRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All Local IVR for campaign
         * @summary Get All Local IVR for campaign
         * @param {number} campaignId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocalIVRForCampaign: async (campaignId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'campaignId' is not null or undefined
            assertParamExists('getLocalIVRForCampaign', 'campaignId', campaignId)
            const localVarPath = `/voice/localIVR/{campaignId}`
                .replace('{campaignId}', encodeURIComponent(String(campaignId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Local IVR
         * @summary Update Local IVR
         * @param {number} localIVRId 
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyLocalIVRForCampaign: async (localIVRId: number, localIVRRequest: LocalIVRRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'localIVRId' is not null or undefined
            assertParamExists('modifyLocalIVRForCampaign', 'localIVRId', localIVRId)
            // verify required parameter 'localIVRRequest' is not null or undefined
            assertParamExists('modifyLocalIVRForCampaign', 'localIVRRequest', localIVRRequest)
            const localVarPath = `/voice/localIVR/{localIVRId}`
                .replace('{localIVRId}', encodeURIComponent(String(localIVRId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(localIVRRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Local IVR
         * @summary Remove Local IVR
         * @param {number} localIVRId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeLocalIVRForCampaign: async (localIVRId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'localIVRId' is not null or undefined
            assertParamExists('removeLocalIVRForCampaign', 'localIVRId', localIVRId)
            const localVarPath = `/voice/localIVR/{localIVRId}`
                .replace('{localIVRId}', encodeURIComponent(String(localIVRId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LocalIVRApi - functional programming interface
 */
export const LocalIVRApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LocalIVRApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Local IVR
         * @summary Add Local IVR
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLocalIVRForCampaign(localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocalIVR>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLocalIVRForCampaign(localIVRRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocalIVRApi.addLocalIVRForCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All Local IVR for campaign
         * @summary Get All Local IVR for campaign
         * @param {number} campaignId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLocalIVRForCampaign(campaignId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LocalIVR>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLocalIVRForCampaign(campaignId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocalIVRApi.getLocalIVRForCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Local IVR
         * @summary Update Local IVR
         * @param {number} localIVRId 
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async modifyLocalIVRForCampaign(localIVRId: number, localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LocalIVR>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.modifyLocalIVRForCampaign(localIVRId, localIVRRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocalIVRApi.modifyLocalIVRForCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Local IVR
         * @summary Remove Local IVR
         * @param {number} localIVRId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeLocalIVRForCampaign(localIVRId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeLocalIVRForCampaign(localIVRId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LocalIVRApi.removeLocalIVRForCampaign']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LocalIVRApi - factory interface
 */
export const LocalIVRApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LocalIVRApiFp(configuration)
    return {
        /**
         * Add Local IVR
         * @summary Add Local IVR
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLocalIVRForCampaign(localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocalIVR> {
            return localVarFp.addLocalIVRForCampaign(localIVRRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All Local IVR for campaign
         * @summary Get All Local IVR for campaign
         * @param {number} campaignId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLocalIVRForCampaign(campaignId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LocalIVR>> {
            return localVarFp.getLocalIVRForCampaign(campaignId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Local IVR
         * @summary Update Local IVR
         * @param {number} localIVRId 
         * @param {LocalIVRRequest} localIVRRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        modifyLocalIVRForCampaign(localIVRId: number, localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig): AxiosPromise<LocalIVR> {
            return localVarFp.modifyLocalIVRForCampaign(localIVRId, localIVRRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Local IVR
         * @summary Remove Local IVR
         * @param {number} localIVRId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeLocalIVRForCampaign(localIVRId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeLocalIVRForCampaign(localIVRId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LocalIVRApi - object-oriented interface
 */
export class LocalIVRApi extends BaseAPI {
    /**
     * Add Local IVR
     * @summary Add Local IVR
     * @param {LocalIVRRequest} localIVRRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addLocalIVRForCampaign(localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig) {
        return LocalIVRApiFp(this.configuration).addLocalIVRForCampaign(localIVRRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All Local IVR for campaign
     * @summary Get All Local IVR for campaign
     * @param {number} campaignId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLocalIVRForCampaign(campaignId: number, options?: RawAxiosRequestConfig) {
        return LocalIVRApiFp(this.configuration).getLocalIVRForCampaign(campaignId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Local IVR
     * @summary Update Local IVR
     * @param {number} localIVRId 
     * @param {LocalIVRRequest} localIVRRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public modifyLocalIVRForCampaign(localIVRId: number, localIVRRequest: LocalIVRRequest, options?: RawAxiosRequestConfig) {
        return LocalIVRApiFp(this.configuration).modifyLocalIVRForCampaign(localIVRId, localIVRRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Local IVR
     * @summary Remove Local IVR
     * @param {number} localIVRId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeLocalIVRForCampaign(localIVRId: number, options?: RawAxiosRequestConfig) {
        return LocalIVRApiFp(this.configuration).removeLocalIVRForCampaign(localIVRId, options).then((request) => request(this.axios, this.basePath));
    }
}

