/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { MaskingPolicyRequest } from '../models';
// @ts-ignore
import type { MaskingPolicyResponse } from '../models';
// @ts-ignore
import type { MaskingPolicyUpdateResponse } from '../models';
/**
 * MaskingPolicyApi - axios parameter creator
 */
export const MaskingPolicyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get All Masking Policies for all Processes of ContactCenter
         * @summary Get All Masking Policies for all Processes of ContactCenter
         * @param {number} contactCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMaskingPoliciesForAllProcessesInContactCenter: async (contactCenterId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllMaskingPoliciesForAllProcessesInContactCenter', 'contactCenterId', contactCenterId)
            const localVarPath = `/customermanagerconfig/maskingPolicy/getMaskingPolicyForAllProcessesInCC/{contactCenterId}`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Masking Policies for Processes
         * @summary Update Masking Policies for Processes
         * @param {Array<MaskingPolicyRequest>} maskingPolicyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMaskingPolicyForProcesses: async (maskingPolicyRequest: Array<MaskingPolicyRequest>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'maskingPolicyRequest' is not null or undefined
            assertParamExists('setMaskingPolicyForProcesses', 'maskingPolicyRequest', maskingPolicyRequest)
            const localVarPath = `/customermanagerconfig/maskingPolicy/updateMaskingPolicyForProcesses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(maskingPolicyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MaskingPolicyApi - functional programming interface
 */
export const MaskingPolicyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MaskingPolicyApiAxiosParamCreator(configuration)
    return {
        /**
         * Get All Masking Policies for all Processes of ContactCenter
         * @summary Get All Masking Policies for all Processes of ContactCenter
         * @param {number} contactCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MaskingPolicyResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MaskingPolicyApi.getAllMaskingPoliciesForAllProcessesInContactCenter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Masking Policies for Processes
         * @summary Update Masking Policies for Processes
         * @param {Array<MaskingPolicyRequest>} maskingPolicyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setMaskingPolicyForProcesses(maskingPolicyRequest: Array<MaskingPolicyRequest>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MaskingPolicyUpdateResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setMaskingPolicyForProcesses(maskingPolicyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MaskingPolicyApi.setMaskingPolicyForProcesses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MaskingPolicyApi - factory interface
 */
export const MaskingPolicyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MaskingPolicyApiFp(configuration)
    return {
        /**
         * Get All Masking Policies for all Processes of ContactCenter
         * @summary Get All Masking Policies for all Processes of ContactCenter
         * @param {number} contactCenterId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<MaskingPolicyResponse>> {
            return localVarFp.getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Masking Policies for Processes
         * @summary Update Masking Policies for Processes
         * @param {Array<MaskingPolicyRequest>} maskingPolicyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setMaskingPolicyForProcesses(maskingPolicyRequest: Array<MaskingPolicyRequest>, options?: RawAxiosRequestConfig): AxiosPromise<Array<MaskingPolicyUpdateResponse>> {
            return localVarFp.setMaskingPolicyForProcesses(maskingPolicyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MaskingPolicyApi - object-oriented interface
 */
export class MaskingPolicyApi extends BaseAPI {
    /**
     * Get All Masking Policies for all Processes of ContactCenter
     * @summary Get All Masking Policies for all Processes of ContactCenter
     * @param {number} contactCenterId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId: number, options?: RawAxiosRequestConfig) {
        return MaskingPolicyApiFp(this.configuration).getAllMaskingPoliciesForAllProcessesInContactCenter(contactCenterId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Masking Policies for Processes
     * @summary Update Masking Policies for Processes
     * @param {Array<MaskingPolicyRequest>} maskingPolicyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setMaskingPolicyForProcesses(maskingPolicyRequest: Array<MaskingPolicyRequest>, options?: RawAxiosRequestConfig) {
        return MaskingPolicyApiFp(this.configuration).setMaskingPolicyForProcesses(maskingPolicyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

