/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkChartOperationRequest } from '../models';
// @ts-ignore
import type { CommonResponseCustomDataResponseChartConfigurationVoid } from '../models';
// @ts-ignore
import type { CommonResponseListCustomDataResponseChartConfigurationVoid } from '../models';
// @ts-ignore
import type { CommonResponseListCustomDataResponseChartResponseCustomOffsetMetadata } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
/**
 * MultiCCManagerChartApi - axios parameter creator
 */
export const MultiCCManagerChartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Assign chart to given tenant
         * @summary Assign Chart to CC
         * @param {number} ccId ID of contact center
         * @param {string} chartTemplateId Chart template ID from Superset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignChartToCC: async (ccId: number, chartTemplateId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('assignChartToCC', 'ccId', ccId)
            // verify required parameter 'chartTemplateId' is not null or undefined
            assertParamExists('assignChartToCC', 'chartTemplateId', chartTemplateId)
            const localVarPath = `/v4/cc-list/{cc-id}/charts/{chart-template-id}`
                .replace('{cc-id}', encodeURIComponent(String(ccId)))
                .replace('{chart-template-id}', encodeURIComponent(String(chartTemplateId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Assign chart to multiple contact centers.
         * @summary Bulk Assign Chart to CC
         * @param {BulkChartOperationRequest} bulkChartOperationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAssignChartToCC: async (bulkChartOperationRequest: BulkChartOperationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkChartOperationRequest' is not null or undefined
            assertParamExists('bulkAssignChartToCC', 'bulkChartOperationRequest', bulkChartOperationRequest)
            const localVarPath = `/v4/bulk-chart-operations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkChartOperationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all charts in superset for Multi CC role
         * @summary Get Charts in Superset
         * @param {number} [offset] Zero-based Offset of the first entry included in this page (0..N)
         * @param {number} [limit] Number of results to be returned
         * @param {Array<string>} [sortBy] Sorting criteria in the format: property:asc|desc, Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCharts: async (offset?: number, limit?: number, sortBy?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v4/charts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Unassign chart for given tenant
         * @summary Unassign Chart from CC
         * @param {number} ccId ID of contact center
         * @param {number} chartId ID of CC chart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignChartFromCC: async (ccId: number, chartId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ccId' is not null or undefined
            assertParamExists('unassignChartFromCC', 'ccId', ccId)
            // verify required parameter 'chartId' is not null or undefined
            assertParamExists('unassignChartFromCC', 'chartId', chartId)
            const localVarPath = `/v4/cc-list/{cc-id}/charts/{chart-id}`
                .replace('{cc-id}', encodeURIComponent(String(ccId)))
                .replace('{chart-id}', encodeURIComponent(String(chartId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MultiCCManagerChartApi - functional programming interface
 */
export const MultiCCManagerChartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MultiCCManagerChartApiAxiosParamCreator(configuration)
    return {
        /**
         * Assign chart to given tenant
         * @summary Assign Chart to CC
         * @param {number} ccId ID of contact center
         * @param {string} chartTemplateId Chart template ID from Superset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assignChartToCC(ccId: number, chartTemplateId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseCustomDataResponseChartConfigurationVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assignChartToCC(ccId, chartTemplateId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MultiCCManagerChartApi.assignChartToCC']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Assign chart to multiple contact centers.
         * @summary Bulk Assign Chart to CC
         * @param {BulkChartOperationRequest} bulkChartOperationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkAssignChartToCC(bulkChartOperationRequest: BulkChartOperationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseListCustomDataResponseChartConfigurationVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkAssignChartToCC(bulkChartOperationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MultiCCManagerChartApi.bulkAssignChartToCC']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all charts in superset for Multi CC role
         * @summary Get Charts in Superset
         * @param {number} [offset] Zero-based Offset of the first entry included in this page (0..N)
         * @param {number} [limit] Number of results to be returned
         * @param {Array<string>} [sortBy] Sorting criteria in the format: property:asc|desc, Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllCharts(offset?: number, limit?: number, sortBy?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseListCustomDataResponseChartResponseCustomOffsetMetadata>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCharts(offset, limit, sortBy, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MultiCCManagerChartApi.getAllCharts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Unassign chart for given tenant
         * @summary Unassign Chart from CC
         * @param {number} ccId ID of contact center
         * @param {number} chartId ID of CC chart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unassignChartFromCC(ccId: number, chartId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unassignChartFromCC(ccId, chartId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MultiCCManagerChartApi.unassignChartFromCC']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MultiCCManagerChartApi - factory interface
 */
export const MultiCCManagerChartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MultiCCManagerChartApiFp(configuration)
    return {
        /**
         * Assign chart to given tenant
         * @summary Assign Chart to CC
         * @param {number} ccId ID of contact center
         * @param {string} chartTemplateId Chart template ID from Superset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assignChartToCC(ccId: number, chartTemplateId: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseCustomDataResponseChartConfigurationVoid> {
            return localVarFp.assignChartToCC(ccId, chartTemplateId, options).then((request) => request(axios, basePath));
        },
        /**
         * Assign chart to multiple contact centers.
         * @summary Bulk Assign Chart to CC
         * @param {BulkChartOperationRequest} bulkChartOperationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkAssignChartToCC(bulkChartOperationRequest: BulkChartOperationRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseListCustomDataResponseChartConfigurationVoid> {
            return localVarFp.bulkAssignChartToCC(bulkChartOperationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all charts in superset for Multi CC role
         * @summary Get Charts in Superset
         * @param {number} [offset] Zero-based Offset of the first entry included in this page (0..N)
         * @param {number} [limit] Number of results to be returned
         * @param {Array<string>} [sortBy] Sorting criteria in the format: property:asc|desc, Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCharts(offset?: number, limit?: number, sortBy?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseListCustomDataResponseChartResponseCustomOffsetMetadata> {
            return localVarFp.getAllCharts(offset, limit, sortBy, options).then((request) => request(axios, basePath));
        },
        /**
         * Unassign chart for given tenant
         * @summary Unassign Chart from CC
         * @param {number} ccId ID of contact center
         * @param {number} chartId ID of CC chart
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unassignChartFromCC(ccId: number, chartId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unassignChartFromCC(ccId, chartId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MultiCCManagerChartApi - object-oriented interface
 */
export class MultiCCManagerChartApi extends BaseAPI {
    /**
     * Assign chart to given tenant
     * @summary Assign Chart to CC
     * @param {number} ccId ID of contact center
     * @param {string} chartTemplateId Chart template ID from Superset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public assignChartToCC(ccId: number, chartTemplateId: string, options?: RawAxiosRequestConfig) {
        return MultiCCManagerChartApiFp(this.configuration).assignChartToCC(ccId, chartTemplateId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Assign chart to multiple contact centers.
     * @summary Bulk Assign Chart to CC
     * @param {BulkChartOperationRequest} bulkChartOperationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public bulkAssignChartToCC(bulkChartOperationRequest: BulkChartOperationRequest, options?: RawAxiosRequestConfig) {
        return MultiCCManagerChartApiFp(this.configuration).bulkAssignChartToCC(bulkChartOperationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all charts in superset for Multi CC role
     * @summary Get Charts in Superset
     * @param {number} [offset] Zero-based Offset of the first entry included in this page (0..N)
     * @param {number} [limit] Number of results to be returned
     * @param {Array<string>} [sortBy] Sorting criteria in the format: property:asc|desc, Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllCharts(offset?: number, limit?: number, sortBy?: Array<string>, options?: RawAxiosRequestConfig) {
        return MultiCCManagerChartApiFp(this.configuration).getAllCharts(offset, limit, sortBy, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Unassign chart for given tenant
     * @summary Unassign Chart from CC
     * @param {number} ccId ID of contact center
     * @param {number} chartId ID of CC chart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unassignChartFromCC(ccId: number, chartId: number, options?: RawAxiosRequestConfig) {
        return MultiCCManagerChartApiFp(this.configuration).unassignChartFromCC(ccId, chartId, options).then((request) => request(this.axios, this.basePath));
    }
}

