/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { OpenAuthConsumerConfiguration } from '../models';
// @ts-ignore
import type { OpenAuthConsumerConfigurationRequest } from '../models';
// @ts-ignore
import type { UpdateOpenAuthConsumerConfigurationRequest } from '../models';
/**
 * OpenAuthConsumerConfigurationApi - axios parameter creator
 */
export const OpenAuthConsumerConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Open Auth Consumer Configuration
         * @summary Add Open Auth Consumer Configuration
         * @param {OpenAuthConsumerConfigurationRequest} openAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOpenAuthConsumerConfiguration: async (openAuthConsumerConfigurationRequest: OpenAuthConsumerConfigurationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'openAuthConsumerConfigurationRequest' is not null or undefined
            assertParamExists('addOpenAuthConsumerConfiguration', 'openAuthConsumerConfigurationRequest', openAuthConsumerConfigurationRequest)
            const localVarPath = `/oauthconfig/openAuthConsumerConfiguration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(openAuthConsumerConfigurationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete Open Auth Consumer Configuration
         * @summary Delete Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOpenAuthConsumerConfiguration: async (consumerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'consumerId' is not null or undefined
            assertParamExists('deleteOpenAuthConsumerConfiguration', 'consumerId', consumerId)
            const localVarPath = `/oauthconfig/openAuthConsumerConfiguration/{consumerId}`
                .replace('{consumerId}', encodeURIComponent(String(consumerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Read Open Auth Consumer Configuration
         * @summary Read Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenAuthConsumerConfiguration: async (consumerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'consumerId' is not null or undefined
            assertParamExists('getOpenAuthConsumerConfiguration', 'consumerId', consumerId)
            const localVarPath = `/oauthconfig/openAuthConsumerConfiguration/{consumerId}`
                .replace('{consumerId}', encodeURIComponent(String(consumerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Open Auth Consumer Configuration
         * @summary Update Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {UpdateOpenAuthConsumerConfigurationRequest} updateOpenAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOpenAuthConsumerConfiguration: async (consumerId: number, updateOpenAuthConsumerConfigurationRequest: UpdateOpenAuthConsumerConfigurationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'consumerId' is not null or undefined
            assertParamExists('updateOpenAuthConsumerConfiguration', 'consumerId', consumerId)
            // verify required parameter 'updateOpenAuthConsumerConfigurationRequest' is not null or undefined
            assertParamExists('updateOpenAuthConsumerConfiguration', 'updateOpenAuthConsumerConfigurationRequest', updateOpenAuthConsumerConfigurationRequest)
            const localVarPath = `/oauthconfig/openAuthConsumerConfiguration/{consumerId}`
                .replace('{consumerId}', encodeURIComponent(String(consumerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOpenAuthConsumerConfigurationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OpenAuthConsumerConfigurationApi - functional programming interface
 */
export const OpenAuthConsumerConfigurationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OpenAuthConsumerConfigurationApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Open Auth Consumer Configuration
         * @summary Add Open Auth Consumer Configuration
         * @param {OpenAuthConsumerConfigurationRequest} openAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest: OpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OpenAuthConsumerConfiguration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAuthConsumerConfigurationApi.addOpenAuthConsumerConfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete Open Auth Consumer Configuration
         * @summary Delete Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOpenAuthConsumerConfiguration(consumerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAuthConsumerConfigurationApi.deleteOpenAuthConsumerConfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Read Open Auth Consumer Configuration
         * @summary Read Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OpenAuthConsumerConfiguration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOpenAuthConsumerConfiguration(consumerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAuthConsumerConfigurationApi.getOpenAuthConsumerConfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Open Auth Consumer Configuration
         * @summary Update Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {UpdateOpenAuthConsumerConfigurationRequest} updateOpenAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOpenAuthConsumerConfiguration(consumerId: number, updateOpenAuthConsumerConfigurationRequest: UpdateOpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OpenAuthConsumerConfiguration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOpenAuthConsumerConfiguration(consumerId, updateOpenAuthConsumerConfigurationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OpenAuthConsumerConfigurationApi.updateOpenAuthConsumerConfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OpenAuthConsumerConfigurationApi - factory interface
 */
export const OpenAuthConsumerConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OpenAuthConsumerConfigurationApiFp(configuration)
    return {
        /**
         * Add Open Auth Consumer Configuration
         * @summary Add Open Auth Consumer Configuration
         * @param {OpenAuthConsumerConfigurationRequest} openAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest: OpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OpenAuthConsumerConfiguration> {
            return localVarFp.addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete Open Auth Consumer Configuration
         * @summary Delete Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteOpenAuthConsumerConfiguration(consumerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Read Open Auth Consumer Configuration
         * @summary Read Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig): AxiosPromise<OpenAuthConsumerConfiguration> {
            return localVarFp.getOpenAuthConsumerConfiguration(consumerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Open Auth Consumer Configuration
         * @summary Update Open Auth Consumer Configuration
         * @param {number} consumerId 
         * @param {UpdateOpenAuthConsumerConfigurationRequest} updateOpenAuthConsumerConfigurationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOpenAuthConsumerConfiguration(consumerId: number, updateOpenAuthConsumerConfigurationRequest: UpdateOpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OpenAuthConsumerConfiguration> {
            return localVarFp.updateOpenAuthConsumerConfiguration(consumerId, updateOpenAuthConsumerConfigurationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OpenAuthConsumerConfigurationApi - object-oriented interface
 */
export class OpenAuthConsumerConfigurationApi extends BaseAPI {
    /**
     * Add Open Auth Consumer Configuration
     * @summary Add Open Auth Consumer Configuration
     * @param {OpenAuthConsumerConfigurationRequest} openAuthConsumerConfigurationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest: OpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig) {
        return OpenAuthConsumerConfigurationApiFp(this.configuration).addOpenAuthConsumerConfiguration(openAuthConsumerConfigurationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete Open Auth Consumer Configuration
     * @summary Delete Open Auth Consumer Configuration
     * @param {number} consumerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig) {
        return OpenAuthConsumerConfigurationApiFp(this.configuration).deleteOpenAuthConsumerConfiguration(consumerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Read Open Auth Consumer Configuration
     * @summary Read Open Auth Consumer Configuration
     * @param {number} consumerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOpenAuthConsumerConfiguration(consumerId: number, options?: RawAxiosRequestConfig) {
        return OpenAuthConsumerConfigurationApiFp(this.configuration).getOpenAuthConsumerConfiguration(consumerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Open Auth Consumer Configuration
     * @summary Update Open Auth Consumer Configuration
     * @param {number} consumerId 
     * @param {UpdateOpenAuthConsumerConfigurationRequest} updateOpenAuthConsumerConfigurationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateOpenAuthConsumerConfiguration(consumerId: number, updateOpenAuthConsumerConfigurationRequest: UpdateOpenAuthConsumerConfigurationRequest, options?: RawAxiosRequestConfig) {
        return OpenAuthConsumerConfigurationApiFp(this.configuration).updateOpenAuthConsumerConfiguration(consumerId, updateOpenAuthConsumerConfigurationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

