/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { RuleRequest } from '../models';
/**
 * RuleEngineRuleApi - axios parameter creator
 */
export const RuleEngineRuleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create Rule Engine Rule
         * @summary Create Rule Engine Rule
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRule: async (ruleRequest: RuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ruleRequest' is not null or undefined
            assertParamExists('createRule', 'ruleRequest', ruleRequest)
            const localVarPath = `/ruleEngine/rule`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ruleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete Rule Engine Rules
         * @summary Delete Rule Engine Rules
         * @param {Array<number>} ruleIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRules: async (ruleIds: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ruleIds' is not null or undefined
            assertParamExists('deleteRules', 'ruleIds', ruleIds)
            const localVarPath = `/ruleEngine/rule`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (ruleIds) {
                localVarQueryParameter['ruleIds'] = ruleIds;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All Rule Engine Rules for event type
         * @summary Get All Rule Engine Rules for event type
         * @param {number} contactCenterId 
         * @param {Array<GetAllRuleForEventTypeEventTypesEnum>} eventTypes 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRuleForEventType: async (contactCenterId: number, eventTypes: Array<GetAllRuleForEventTypeEventTypesEnum>, enabledOnly: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllRuleForEventType', 'contactCenterId', contactCenterId)
            // verify required parameter 'eventTypes' is not null or undefined
            assertParamExists('getAllRuleForEventType', 'eventTypes', eventTypes)
            // verify required parameter 'enabledOnly' is not null or undefined
            assertParamExists('getAllRuleForEventType', 'enabledOnly', enabledOnly)
            const localVarPath = `/ruleEngine/rule/{contactCenterId}/getAllRulesByEventType`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (eventTypes) {
                localVarQueryParameter['eventTypes'] = eventTypes;
            }

            if (enabledOnly !== undefined) {
                localVarQueryParameter['enabledOnly'] = enabledOnly;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All Rule Engine Rules for rule type
         * @summary Get All Rule Engine Rules for rule type
         * @param {number} contactCenterId 
         * @param {GetAllRuleForGivenRuleTypeRuleTypeEnum} ruleType 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRuleForGivenRuleType: async (contactCenterId: number, ruleType: GetAllRuleForGivenRuleTypeRuleTypeEnum, enabledOnly: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllRuleForGivenRuleType', 'contactCenterId', contactCenterId)
            // verify required parameter 'ruleType' is not null or undefined
            assertParamExists('getAllRuleForGivenRuleType', 'ruleType', ruleType)
            // verify required parameter 'enabledOnly' is not null or undefined
            assertParamExists('getAllRuleForGivenRuleType', 'enabledOnly', enabledOnly)
            const localVarPath = `/ruleEngine/rule/{contactCenterId}/getAllRulesByRuleType`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (ruleType !== undefined) {
                localVarQueryParameter['ruleType'] = ruleType;
            }

            if (enabledOnly !== undefined) {
                localVarQueryParameter['enabledOnly'] = enabledOnly;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get All Rule Engine Rules for event type and context
         * @summary Get All Rule Engine Rules for event type and context
         * @param {number} contactCenterId 
         * @param {Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>} eventList 
         * @param {boolean} enabledOnly 
         * @param {GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum} contextType 
         * @param {number} contextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRulesForEventTypesAndContextTypeAndContextId: async (contactCenterId: number, eventList: Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>, enabledOnly: boolean, contextType: GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum, contextId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contactCenterId' is not null or undefined
            assertParamExists('getAllRulesForEventTypesAndContextTypeAndContextId', 'contactCenterId', contactCenterId)
            // verify required parameter 'eventList' is not null or undefined
            assertParamExists('getAllRulesForEventTypesAndContextTypeAndContextId', 'eventList', eventList)
            // verify required parameter 'enabledOnly' is not null or undefined
            assertParamExists('getAllRulesForEventTypesAndContextTypeAndContextId', 'enabledOnly', enabledOnly)
            // verify required parameter 'contextType' is not null or undefined
            assertParamExists('getAllRulesForEventTypesAndContextTypeAndContextId', 'contextType', contextType)
            // verify required parameter 'contextId' is not null or undefined
            assertParamExists('getAllRulesForEventTypesAndContextTypeAndContextId', 'contextId', contextId)
            const localVarPath = `/ruleEngine/rule/{contactCenterId}/getAllRulesByEventTypeAndContext`
                .replace('{contactCenterId}', encodeURIComponent(String(contactCenterId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (eventList) {
                localVarQueryParameter['eventList'] = eventList;
            }

            if (enabledOnly !== undefined) {
                localVarQueryParameter['enabledOnly'] = enabledOnly;
            }

            if (contextType !== undefined) {
                localVarQueryParameter['contextType'] = contextType;
            }

            if (contextId !== undefined) {
                localVarQueryParameter['contextId'] = contextId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Rule Engine Rule By Id
         * @summary Get Rule Engine Rule By Id
         * @param {number} ruleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRuleById: async (ruleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ruleId' is not null or undefined
            assertParamExists('getRuleById', 'ruleId', ruleId)
            const localVarPath = `/ruleEngine/rule/{ruleId}`
                .replace('{ruleId}', encodeURIComponent(String(ruleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Rule Engine Rule
         * @summary Update Rule Engine Rule
         * @param {number} ruleId 
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRule: async (ruleId: number, ruleRequest: RuleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ruleId' is not null or undefined
            assertParamExists('updateRule', 'ruleId', ruleId)
            // verify required parameter 'ruleRequest' is not null or undefined
            assertParamExists('updateRule', 'ruleRequest', ruleRequest)
            const localVarPath = `/ruleEngine/rule/{ruleId}`
                .replace('{ruleId}', encodeURIComponent(String(ruleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ruleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Rule Engine Rules
         * @summary Update Rule Engine Rules
         * @param {Array<RuleRequest>} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRules: async (ruleRequest: Array<RuleRequest>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ruleRequest' is not null or undefined
            assertParamExists('updateRules', 'ruleRequest', ruleRequest)
            const localVarPath = `/ruleEngine/rule/updateRules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ruleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RuleEngineRuleApi - functional programming interface
 */
export const RuleEngineRuleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RuleEngineRuleApiAxiosParamCreator(configuration)
    return {
        /**
         * Create Rule Engine Rule
         * @summary Create Rule Engine Rule
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRule(ruleRequest: RuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuleRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRule(ruleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.createRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete Rule Engine Rules
         * @summary Delete Rule Engine Rules
         * @param {Array<number>} ruleIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteRules(ruleIds: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRules(ruleIds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.deleteRules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All Rule Engine Rules for event type
         * @summary Get All Rule Engine Rules for event type
         * @param {number} contactCenterId 
         * @param {Array<GetAllRuleForEventTypeEventTypesEnum>} eventTypes 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllRuleForEventType(contactCenterId: number, eventTypes: Array<GetAllRuleForEventTypeEventTypesEnum>, enabledOnly: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RuleRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllRuleForEventType(contactCenterId, eventTypes, enabledOnly, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.getAllRuleForEventType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All Rule Engine Rules for rule type
         * @summary Get All Rule Engine Rules for rule type
         * @param {number} contactCenterId 
         * @param {GetAllRuleForGivenRuleTypeRuleTypeEnum} ruleType 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllRuleForGivenRuleType(contactCenterId: number, ruleType: GetAllRuleForGivenRuleTypeRuleTypeEnum, enabledOnly: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RuleRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllRuleForGivenRuleType(contactCenterId, ruleType, enabledOnly, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.getAllRuleForGivenRuleType']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get All Rule Engine Rules for event type and context
         * @summary Get All Rule Engine Rules for event type and context
         * @param {number} contactCenterId 
         * @param {Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>} eventList 
         * @param {boolean} enabledOnly 
         * @param {GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum} contextType 
         * @param {number} contextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId: number, eventList: Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>, enabledOnly: boolean, contextType: GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum, contextId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<RuleRequest>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId, eventList, enabledOnly, contextType, contextId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.getAllRulesForEventTypesAndContextTypeAndContextId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Rule Engine Rule By Id
         * @summary Get Rule Engine Rule By Id
         * @param {number} ruleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRuleById(ruleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuleRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRuleById(ruleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.getRuleById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Rule Engine Rule
         * @summary Update Rule Engine Rule
         * @param {number} ruleId 
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRule(ruleId: number, ruleRequest: RuleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RuleRequest>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRule(ruleId, ruleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.updateRule']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Rule Engine Rules
         * @summary Update Rule Engine Rules
         * @param {Array<RuleRequest>} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateRules(ruleRequest: Array<RuleRequest>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateRules(ruleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RuleEngineRuleApi.updateRules']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RuleEngineRuleApi - factory interface
 */
export const RuleEngineRuleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RuleEngineRuleApiFp(configuration)
    return {
        /**
         * Create Rule Engine Rule
         * @summary Create Rule Engine Rule
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRule(ruleRequest: RuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<RuleRequest> {
            return localVarFp.createRule(ruleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete Rule Engine Rules
         * @summary Delete Rule Engine Rules
         * @param {Array<number>} ruleIds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteRules(ruleIds: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteRules(ruleIds, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All Rule Engine Rules for event type
         * @summary Get All Rule Engine Rules for event type
         * @param {number} contactCenterId 
         * @param {Array<GetAllRuleForEventTypeEventTypesEnum>} eventTypes 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRuleForEventType(contactCenterId: number, eventTypes: Array<GetAllRuleForEventTypeEventTypesEnum>, enabledOnly: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<RuleRequest>> {
            return localVarFp.getAllRuleForEventType(contactCenterId, eventTypes, enabledOnly, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All Rule Engine Rules for rule type
         * @summary Get All Rule Engine Rules for rule type
         * @param {number} contactCenterId 
         * @param {GetAllRuleForGivenRuleTypeRuleTypeEnum} ruleType 
         * @param {boolean} enabledOnly 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRuleForGivenRuleType(contactCenterId: number, ruleType: GetAllRuleForGivenRuleTypeRuleTypeEnum, enabledOnly: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<RuleRequest>> {
            return localVarFp.getAllRuleForGivenRuleType(contactCenterId, ruleType, enabledOnly, options).then((request) => request(axios, basePath));
        },
        /**
         * Get All Rule Engine Rules for event type and context
         * @summary Get All Rule Engine Rules for event type and context
         * @param {number} contactCenterId 
         * @param {Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>} eventList 
         * @param {boolean} enabledOnly 
         * @param {GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum} contextType 
         * @param {number} contextId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId: number, eventList: Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>, enabledOnly: boolean, contextType: GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum, contextId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<RuleRequest>> {
            return localVarFp.getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId, eventList, enabledOnly, contextType, contextId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Rule Engine Rule By Id
         * @summary Get Rule Engine Rule By Id
         * @param {number} ruleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRuleById(ruleId: number, options?: RawAxiosRequestConfig): AxiosPromise<RuleRequest> {
            return localVarFp.getRuleById(ruleId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Rule Engine Rule
         * @summary Update Rule Engine Rule
         * @param {number} ruleId 
         * @param {RuleRequest} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRule(ruleId: number, ruleRequest: RuleRequest, options?: RawAxiosRequestConfig): AxiosPromise<RuleRequest> {
            return localVarFp.updateRule(ruleId, ruleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Rule Engine Rules
         * @summary Update Rule Engine Rules
         * @param {Array<RuleRequest>} ruleRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateRules(ruleRequest: Array<RuleRequest>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateRules(ruleRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RuleEngineRuleApi - object-oriented interface
 */
export class RuleEngineRuleApi extends BaseAPI {
    /**
     * Create Rule Engine Rule
     * @summary Create Rule Engine Rule
     * @param {RuleRequest} ruleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createRule(ruleRequest: RuleRequest, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).createRule(ruleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete Rule Engine Rules
     * @summary Delete Rule Engine Rules
     * @param {Array<number>} ruleIds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteRules(ruleIds: Array<number>, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).deleteRules(ruleIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All Rule Engine Rules for event type
     * @summary Get All Rule Engine Rules for event type
     * @param {number} contactCenterId 
     * @param {Array<GetAllRuleForEventTypeEventTypesEnum>} eventTypes 
     * @param {boolean} enabledOnly 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllRuleForEventType(contactCenterId: number, eventTypes: Array<GetAllRuleForEventTypeEventTypesEnum>, enabledOnly: boolean, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).getAllRuleForEventType(contactCenterId, eventTypes, enabledOnly, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All Rule Engine Rules for rule type
     * @summary Get All Rule Engine Rules for rule type
     * @param {number} contactCenterId 
     * @param {GetAllRuleForGivenRuleTypeRuleTypeEnum} ruleType 
     * @param {boolean} enabledOnly 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllRuleForGivenRuleType(contactCenterId: number, ruleType: GetAllRuleForGivenRuleTypeRuleTypeEnum, enabledOnly: boolean, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).getAllRuleForGivenRuleType(contactCenterId, ruleType, enabledOnly, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get All Rule Engine Rules for event type and context
     * @summary Get All Rule Engine Rules for event type and context
     * @param {number} contactCenterId 
     * @param {Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>} eventList 
     * @param {boolean} enabledOnly 
     * @param {GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum} contextType 
     * @param {number} contextId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId: number, eventList: Array<GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum>, enabledOnly: boolean, contextType: GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum, contextId: number, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).getAllRulesForEventTypesAndContextTypeAndContextId(contactCenterId, eventList, enabledOnly, contextType, contextId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Rule Engine Rule By Id
     * @summary Get Rule Engine Rule By Id
     * @param {number} ruleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRuleById(ruleId: number, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).getRuleById(ruleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Rule Engine Rule
     * @summary Update Rule Engine Rule
     * @param {number} ruleId 
     * @param {RuleRequest} ruleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRule(ruleId: number, ruleRequest: RuleRequest, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).updateRule(ruleId, ruleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Rule Engine Rules
     * @summary Update Rule Engine Rules
     * @param {Array<RuleRequest>} ruleRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateRules(ruleRequest: Array<RuleRequest>, options?: RawAxiosRequestConfig) {
        return RuleEngineRuleApiFp(this.configuration).updateRules(ruleRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

export const GetAllRuleForEventTypeEventTypesEnum = {
    ForwardFeedFinishedEvent: 'FORWARD_FEED_FINISHED_EVENT',
    ForwardFeedEvent: 'FORWARD_FEED_EVENT',
    Default: 'DEFAULT',
    UserTransition: 'USER_TRANSITION',
    TenantAllocationEvent: 'TENANT_ALLOCATION_EVENT',
    TenantDeallocationEvent: 'TENANT_DEALLOCATION_EVENT',
    TenantAllocationCompleteEvent: 'TENANT_ALLOCATION_COMPLETE_EVENT',
    ResponderEvent: 'RESPONDER_EVENT',
    DataAllocationEvent: 'DATA_ALLOCATION_EVENT',
    DataDeAllocationEvent: 'DATA_DE_ALLOCATION_EVENT',
    DataReAllocationEvent: 'DATA_RE_ALLOCATION_EVENT',
    IntraReallocation: 'INTRA_REALLOCATION',
    LocalUpload: 'LOCAL_UPLOAD',
    UserIdDataAllocationEvent: 'USER_ID_DATA_ALLOCATION_EVENT',
    AutoAllocationResponse: 'AUTO_ALLOCATION_RESPONSE',
    AssignUser: 'ASSIGN_USER',
    UnassignUser: 'UNASSIGN_USER',
    AbsenteeEvent: 'ABSENTEE_EVENT',
    DialingModeTransitionEvent: 'DIALING_MODE_TRANSITION_EVENT',
    TrailsDeAllocation: 'TRAILS_DE_ALLOCATION',
    SystemDataChangeEvent: 'SYSTEM_DATA_CHANGE_EVENT',
    CustomerDataUpdateEvent: 'CUSTOMER_DATA_UPDATE_EVENT',
    NewCustomersEvent: 'NEW_CUSTOMERS_EVENT',
    AutomationEvent: 'AUTOMATION_EVENT',
    InteractionCreated: 'INTERACTION_CREATED',
    TicketAssignedToAgent: 'TICKET_ASSIGNED_TO_AGENT',
    TicketAgentUpdated: 'TICKET_AGENT_UPDATED',
    TicketTransferredToAgent: 'TICKET_TRANSFERRED_TO_AGENT',
    TicketTransferredToQueue: 'TICKET_TRANSFERRED_TO_QUEUE',
    MessageSent: 'MESSAGE_SENT',
    ChatFeedbackRecevied: 'CHAT_FEEDBACK_RECEVIED',
    HeatValueChanged: 'HEAT_VALUE_CHANGED',
    CustomerOverallPositiveIndexChanged: 'CUSTOMER_OVERALL_POSITIVE_INDEX_CHANGED',
    CustomerCurrentPositiveIndexChanged: 'CUSTOMER_CURRENT_POSITIVE_INDEX_CHANGED',
    TicketUpdated: 'TICKET_UPDATED',
    ResolveSlaBreached: 'RESOLVE_SLA_BREACHED',
    FirstAssignSlaBreached: 'FIRST_ASSIGN_SLA_BREACHED',
    FirstResponseSlaBreached: 'FIRST_RESPONSE_SLA_BREACHED',
    TicketDeescalated: 'TICKET_DEESCALATED',
    MailSendingFailed: 'MAIL_SENDING_FAILED',
    PublicNoteAdded: 'PUBLIC_NOTE_ADDED',
    PriorityChanged: 'PRIORITY_CHANGED',
    CustomFieldUpdated: 'CUSTOM_FIELD_UPDATED',
    PrivateNoteAdded: 'PRIVATE_NOTE_ADDED',
    TicketSplitted: 'TICKET_SPLITTED',
    TicketMerged: 'TICKET_MERGED',
    TicketEscalated: 'TICKET_ESCALATED',
    InteractionEscalated: 'INTERACTION_ESCALATED',
    TicketStatusChanged: 'TICKET_STATUS_CHANGED',
    TicketReopened: 'TICKET_REOPENED',
    NewMessageReceived: 'NEW_MESSAGE_RECEIVED',
    ReplySent: 'REPLY_SENT',
    NewTicketCreated: 'NEW_TICKET_CREATED',
    TicketPickedManually: 'TICKET_PICKED_MANUALLY',
    IncomingEmailConversationCreated: 'INCOMING_EMAIL_CONVERSATION_CREATED',
    ConversationClosed: 'CONVERSATION_CLOSED',
    ConversationReopened: 'CONVERSATION_REOPENED',
    ConversationCreated: 'CONVERSATION_CREATED',
    NewTicketLiteCreated: 'NEW_TICKET_LITE_CREATED',
    IncomingEmailInteractionCreated: 'INCOMING_EMAIL_INTERACTION_CREATED',
    TicketAutoAssigned: 'TICKET_AUTO_ASSIGNED',
    UploadEvent: 'UPLOAD_EVENT',
    AllChildTicketsAreClosed: 'ALL_CHILD_TICKETS_ARE_CLOSED',
    AppointmentReminder: 'APPOINTMENT_REMINDER',
    AppointmentBooked: 'APPOINTMENT_BOOKED',
    AppointmentCancelled: 'APPOINTMENT_CANCELLED',
    AppointmentStatusChanged: 'APPOINTMENT_STATUS_CHANGED',
    AppointmentRescheduled: 'APPOINTMENT_RESCHEDULED',
    AutoUpdateEvent: 'AUTO_UPDATE_EVENT',
} as const;
export type GetAllRuleForEventTypeEventTypesEnum = typeof GetAllRuleForEventTypeEventTypesEnum[keyof typeof GetAllRuleForEventTypeEventTypesEnum];
export const GetAllRuleForGivenRuleTypeRuleTypeEnum = {
    Operation: 'OPERATION',
    Timer: 'TIMER',
    Routing: 'ROUTING',
} as const;
export type GetAllRuleForGivenRuleTypeRuleTypeEnum = typeof GetAllRuleForGivenRuleTypeRuleTypeEnum[keyof typeof GetAllRuleForGivenRuleTypeRuleTypeEnum];
export const GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum = {
    ForwardFeedFinishedEvent: 'FORWARD_FEED_FINISHED_EVENT',
    ForwardFeedEvent: 'FORWARD_FEED_EVENT',
    Default: 'DEFAULT',
    UserTransition: 'USER_TRANSITION',
    TenantAllocationEvent: 'TENANT_ALLOCATION_EVENT',
    TenantDeallocationEvent: 'TENANT_DEALLOCATION_EVENT',
    TenantAllocationCompleteEvent: 'TENANT_ALLOCATION_COMPLETE_EVENT',
    ResponderEvent: 'RESPONDER_EVENT',
    DataAllocationEvent: 'DATA_ALLOCATION_EVENT',
    DataDeAllocationEvent: 'DATA_DE_ALLOCATION_EVENT',
    DataReAllocationEvent: 'DATA_RE_ALLOCATION_EVENT',
    IntraReallocation: 'INTRA_REALLOCATION',
    LocalUpload: 'LOCAL_UPLOAD',
    UserIdDataAllocationEvent: 'USER_ID_DATA_ALLOCATION_EVENT',
    AutoAllocationResponse: 'AUTO_ALLOCATION_RESPONSE',
    AssignUser: 'ASSIGN_USER',
    UnassignUser: 'UNASSIGN_USER',
    AbsenteeEvent: 'ABSENTEE_EVENT',
    DialingModeTransitionEvent: 'DIALING_MODE_TRANSITION_EVENT',
    TrailsDeAllocation: 'TRAILS_DE_ALLOCATION',
    SystemDataChangeEvent: 'SYSTEM_DATA_CHANGE_EVENT',
    CustomerDataUpdateEvent: 'CUSTOMER_DATA_UPDATE_EVENT',
    NewCustomersEvent: 'NEW_CUSTOMERS_EVENT',
    AutomationEvent: 'AUTOMATION_EVENT',
    InteractionCreated: 'INTERACTION_CREATED',
    TicketAssignedToAgent: 'TICKET_ASSIGNED_TO_AGENT',
    TicketAgentUpdated: 'TICKET_AGENT_UPDATED',
    TicketTransferredToAgent: 'TICKET_TRANSFERRED_TO_AGENT',
    TicketTransferredToQueue: 'TICKET_TRANSFERRED_TO_QUEUE',
    MessageSent: 'MESSAGE_SENT',
    ChatFeedbackRecevied: 'CHAT_FEEDBACK_RECEVIED',
    HeatValueChanged: 'HEAT_VALUE_CHANGED',
    CustomerOverallPositiveIndexChanged: 'CUSTOMER_OVERALL_POSITIVE_INDEX_CHANGED',
    CustomerCurrentPositiveIndexChanged: 'CUSTOMER_CURRENT_POSITIVE_INDEX_CHANGED',
    TicketUpdated: 'TICKET_UPDATED',
    ResolveSlaBreached: 'RESOLVE_SLA_BREACHED',
    FirstAssignSlaBreached: 'FIRST_ASSIGN_SLA_BREACHED',
    FirstResponseSlaBreached: 'FIRST_RESPONSE_SLA_BREACHED',
    TicketDeescalated: 'TICKET_DEESCALATED',
    MailSendingFailed: 'MAIL_SENDING_FAILED',
    PublicNoteAdded: 'PUBLIC_NOTE_ADDED',
    PriorityChanged: 'PRIORITY_CHANGED',
    CustomFieldUpdated: 'CUSTOM_FIELD_UPDATED',
    PrivateNoteAdded: 'PRIVATE_NOTE_ADDED',
    TicketSplitted: 'TICKET_SPLITTED',
    TicketMerged: 'TICKET_MERGED',
    TicketEscalated: 'TICKET_ESCALATED',
    InteractionEscalated: 'INTERACTION_ESCALATED',
    TicketStatusChanged: 'TICKET_STATUS_CHANGED',
    TicketReopened: 'TICKET_REOPENED',
    NewMessageReceived: 'NEW_MESSAGE_RECEIVED',
    ReplySent: 'REPLY_SENT',
    NewTicketCreated: 'NEW_TICKET_CREATED',
    TicketPickedManually: 'TICKET_PICKED_MANUALLY',
    IncomingEmailConversationCreated: 'INCOMING_EMAIL_CONVERSATION_CREATED',
    ConversationClosed: 'CONVERSATION_CLOSED',
    ConversationReopened: 'CONVERSATION_REOPENED',
    ConversationCreated: 'CONVERSATION_CREATED',
    NewTicketLiteCreated: 'NEW_TICKET_LITE_CREATED',
    IncomingEmailInteractionCreated: 'INCOMING_EMAIL_INTERACTION_CREATED',
    TicketAutoAssigned: 'TICKET_AUTO_ASSIGNED',
    UploadEvent: 'UPLOAD_EVENT',
    AllChildTicketsAreClosed: 'ALL_CHILD_TICKETS_ARE_CLOSED',
    AppointmentReminder: 'APPOINTMENT_REMINDER',
    AppointmentBooked: 'APPOINTMENT_BOOKED',
    AppointmentCancelled: 'APPOINTMENT_CANCELLED',
    AppointmentStatusChanged: 'APPOINTMENT_STATUS_CHANGED',
    AppointmentRescheduled: 'APPOINTMENT_RESCHEDULED',
    AutoUpdateEvent: 'AUTO_UPDATE_EVENT',
} as const;
export type GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum = typeof GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum[keyof typeof GetAllRulesForEventTypesAndContextTypeAndContextIdEventListEnum];
export const GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum = {
    Process: 'PROCESS',
    ContactCenter: 'CONTACT_CENTER',
    Campaign: 'CAMPAIGN',
    AgentQueue: 'AGENT_QUEUE',
} as const;
export type GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum = typeof GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum[keyof typeof GetAllRulesForEventTypesAndContextTypeAndContextIdContextTypeEnum];
