/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResponse } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
/**
 * ServicePatchingApi - axios parameter creator
 */
export const ServicePatchingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves all database configurations for a specific service name with optional status filter. Returns ACTIVE configs by default. Accepts service names in various formats (e.g., \'chat\', \'CHAT\', \'data-engine\', \'data_engine\').
         * @summary Get all database configurations for a service
         * @param {string} serviceName Service name (e.g., interaction, data-engine, chat) - mandatory
         * @param {string} [status] Status filter (e.g., active, pending, inactive). Defaults to ACTIVE if not provided
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDbConfigs: async (serviceName: string, status?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'serviceName' is not null or undefined
            assertParamExists('getAllDbConfigs', 'serviceName', serviceName)
            const localVarPath = `/api/v1/service/db-configs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (serviceName !== undefined) {
                localVarQueryParameter['serviceName'] = serviceName;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Performs database creation for remote contact centers (if enabled), database schema patching and/or Citus configuration for a specific service across all contact centers that have databases for that service
         * @summary Patch a specific service across all contact centers with databases
         * @param {string} serviceCode Service code (e.g., cqa, ccdp, interaction, data_engine, chat)
         * @param {boolean} [includeDbCreation] Whether to create missing databases for remote contact centers (default: false)
         * @param {boolean} [includePatch] Whether to include Liquibase schema patching (default: true)
         * @param {boolean} [includeCitus] Whether to include Citus initialization and configuration (default: true)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchService: async (serviceCode: string, includeDbCreation?: boolean, includePatch?: boolean, includeCitus?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'serviceCode' is not null or undefined
            assertParamExists('patchService', 'serviceCode', serviceCode)
            const localVarPath = `/api/v1/service/patch/{serviceCode}`
                .replace('{serviceCode}', encodeURIComponent(String(serviceCode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (includeDbCreation !== undefined) {
                localVarQueryParameter['includeDbCreation'] = includeDbCreation;
            }

            if (includePatch !== undefined) {
                localVarQueryParameter['includePatch'] = includePatch;
            }

            if (includeCitus !== undefined) {
                localVarQueryParameter['includeCitus'] = includeCitus;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServicePatchingApi - functional programming interface
 */
export const ServicePatchingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServicePatchingApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves all database configurations for a specific service name with optional status filter. Returns ACTIVE configs by default. Accepts service names in various formats (e.g., \'chat\', \'CHAT\', \'data-engine\', \'data_engine\').
         * @summary Get all database configurations for a service
         * @param {string} serviceName Service name (e.g., interaction, data-engine, chat) - mandatory
         * @param {string} [status] Status filter (e.g., active, pending, inactive). Defaults to ACTIVE if not provided
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDbConfigs(serviceName: string, status?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDbConfigs(serviceName, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServicePatchingApi.getAllDbConfigs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Performs database creation for remote contact centers (if enabled), database schema patching and/or Citus configuration for a specific service across all contact centers that have databases for that service
         * @summary Patch a specific service across all contact centers with databases
         * @param {string} serviceCode Service code (e.g., cqa, ccdp, interaction, data_engine, chat)
         * @param {boolean} [includeDbCreation] Whether to create missing databases for remote contact centers (default: false)
         * @param {boolean} [includePatch] Whether to include Liquibase schema patching (default: true)
         * @param {boolean} [includeCitus] Whether to include Citus initialization and configuration (default: true)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchService(serviceCode: string, includeDbCreation?: boolean, includePatch?: boolean, includeCitus?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchService(serviceCode, includeDbCreation, includePatch, includeCitus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServicePatchingApi.patchService']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServicePatchingApi - factory interface
 */
export const ServicePatchingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServicePatchingApiFp(configuration)
    return {
        /**
         * Retrieves all database configurations for a specific service name with optional status filter. Returns ACTIVE configs by default. Accepts service names in various formats (e.g., \'chat\', \'CHAT\', \'data-engine\', \'data_engine\').
         * @summary Get all database configurations for a service
         * @param {string} serviceName Service name (e.g., interaction, data-engine, chat) - mandatory
         * @param {string} [status] Status filter (e.g., active, pending, inactive). Defaults to ACTIVE if not provided
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDbConfigs(serviceName: string, status?: string, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.getAllDbConfigs(serviceName, status, options).then((request) => request(axios, basePath));
        },
        /**
         * Performs database creation for remote contact centers (if enabled), database schema patching and/or Citus configuration for a specific service across all contact centers that have databases for that service
         * @summary Patch a specific service across all contact centers with databases
         * @param {string} serviceCode Service code (e.g., cqa, ccdp, interaction, data_engine, chat)
         * @param {boolean} [includeDbCreation] Whether to create missing databases for remote contact centers (default: false)
         * @param {boolean} [includePatch] Whether to include Liquibase schema patching (default: true)
         * @param {boolean} [includeCitus] Whether to include Citus initialization and configuration (default: true)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchService(serviceCode: string, includeDbCreation?: boolean, includePatch?: boolean, includeCitus?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponse> {
            return localVarFp.patchService(serviceCode, includeDbCreation, includePatch, includeCitus, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServicePatchingApi - object-oriented interface
 */
export class ServicePatchingApi extends BaseAPI {
    /**
     * Retrieves all database configurations for a specific service name with optional status filter. Returns ACTIVE configs by default. Accepts service names in various formats (e.g., \'chat\', \'CHAT\', \'data-engine\', \'data_engine\').
     * @summary Get all database configurations for a service
     * @param {string} serviceName Service name (e.g., interaction, data-engine, chat) - mandatory
     * @param {string} [status] Status filter (e.g., active, pending, inactive). Defaults to ACTIVE if not provided
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllDbConfigs(serviceName: string, status?: string, options?: RawAxiosRequestConfig) {
        return ServicePatchingApiFp(this.configuration).getAllDbConfigs(serviceName, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Performs database creation for remote contact centers (if enabled), database schema patching and/or Citus configuration for a specific service across all contact centers that have databases for that service
     * @summary Patch a specific service across all contact centers with databases
     * @param {string} serviceCode Service code (e.g., cqa, ccdp, interaction, data_engine, chat)
     * @param {boolean} [includeDbCreation] Whether to create missing databases for remote contact centers (default: false)
     * @param {boolean} [includePatch] Whether to include Liquibase schema patching (default: true)
     * @param {boolean} [includeCitus] Whether to include Citus initialization and configuration (default: true)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public patchService(serviceCode: string, includeDbCreation?: boolean, includePatch?: boolean, includeCitus?: boolean, options?: RawAxiosRequestConfig) {
        return ServicePatchingApiFp(this.configuration).patchService(serviceCode, includeDbCreation, includePatch, includeCitus, options).then((request) => request(this.axios, this.basePath));
    }
}

