/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { Preference } from '../models';
// @ts-ignore
import type { PreferenceRequest } from '../models';
// @ts-ignore
import type { RestSliceResponsePreferenceKeyPreferenceParamRuntimeCacheBean } from '../models';
/**
 * ServerPreferenceApi - axios parameter creator
 */
export const ServerPreferenceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Remove server preference store configuration
         * @summary Remove server preference store configuration
         * @param {string} contextType 
         * @param {string} contextId 
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrefrence: async (contextType: string, contextId: string, key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contextType' is not null or undefined
            assertParamExists('deletePrefrence', 'contextType', contextType)
            // verify required parameter 'contextId' is not null or undefined
            assertParamExists('deletePrefrence', 'contextId', contextId)
            // verify required parameter 'key' is not null or undefined
            assertParamExists('deletePrefrence', 'key', key)
            const localVarPath = `/serverPreference/removePreference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (contextType !== undefined) {
                localVarQueryParameter['contextType'] = contextType;
            }

            if (contextId !== undefined) {
                localVarQueryParameter['contextId'] = contextId;
            }

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all preferneces
         * @summary Fetch all Preference Configurations Paginated
         * @param {number} size 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPreferences: async (size: number, page?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'size' is not null or undefined
            assertParamExists('fetchPreferences', 'size', size)
            const localVarPath = `/serverPreference/fetch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get server preference store configuration
         * @summary Get server preference store configuration
         * @param {string} contextType Context type for preference
         * @param {string} contextId Context Id of context type provided
         * @param {string} key Key name for preference
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreference: async (contextType: string, contextId: string, key: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contextType' is not null or undefined
            assertParamExists('getPreference', 'contextType', contextType)
            // verify required parameter 'contextId' is not null or undefined
            assertParamExists('getPreference', 'contextId', contextId)
            // verify required parameter 'key' is not null or undefined
            assertParamExists('getPreference', 'key', key)
            const localVarPath = `/serverPreference/getPreference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (contextType !== undefined) {
                localVarQueryParameter['contextType'] = contextType;
            }

            if (contextId !== undefined) {
                localVarQueryParameter['contextId'] = contextId;
            }

            if (key !== undefined) {
                localVarQueryParameter['key'] = key;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set server preference store configuration
         * @summary Set server preference store configuration
         * @param {PreferenceRequest} preferenceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setPrefrence: async (preferenceRequest: PreferenceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'preferenceRequest' is not null or undefined
            assertParamExists('setPrefrence', 'preferenceRequest', preferenceRequest)
            const localVarPath = `/serverPreference/setPreference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(preferenceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServerPreferenceApi - functional programming interface
 */
export const ServerPreferenceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServerPreferenceApiAxiosParamCreator(configuration)
    return {
        /**
         * Remove server preference store configuration
         * @summary Remove server preference store configuration
         * @param {string} contextType 
         * @param {string} contextId 
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePrefrence(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Preference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePrefrence(contextType, contextId, key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerPreferenceApi.deletePrefrence']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all preferneces
         * @summary Fetch all Preference Configurations Paginated
         * @param {number} size 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fetchPreferences(size: number, page?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RestSliceResponsePreferenceKeyPreferenceParamRuntimeCacheBean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fetchPreferences(size, page, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerPreferenceApi.fetchPreferences']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get server preference store configuration
         * @summary Get server preference store configuration
         * @param {string} contextType Context type for preference
         * @param {string} contextId Context Id of context type provided
         * @param {string} key Key name for preference
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPreference(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Preference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPreference(contextType, contextId, key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerPreferenceApi.getPreference']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Set server preference store configuration
         * @summary Set server preference store configuration
         * @param {PreferenceRequest} preferenceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setPrefrence(preferenceRequest: PreferenceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Preference>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setPrefrence(preferenceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ServerPreferenceApi.setPrefrence']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ServerPreferenceApi - factory interface
 */
export const ServerPreferenceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServerPreferenceApiFp(configuration)
    return {
        /**
         * Remove server preference store configuration
         * @summary Remove server preference store configuration
         * @param {string} contextType 
         * @param {string} contextId 
         * @param {string} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrefrence(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig): AxiosPromise<Preference> {
            return localVarFp.deletePrefrence(contextType, contextId, key, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all preferneces
         * @summary Fetch all Preference Configurations Paginated
         * @param {number} size 
         * @param {number} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fetchPreferences(size: number, page?: number, options?: RawAxiosRequestConfig): AxiosPromise<RestSliceResponsePreferenceKeyPreferenceParamRuntimeCacheBean> {
            return localVarFp.fetchPreferences(size, page, options).then((request) => request(axios, basePath));
        },
        /**
         * Get server preference store configuration
         * @summary Get server preference store configuration
         * @param {string} contextType Context type for preference
         * @param {string} contextId Context Id of context type provided
         * @param {string} key Key name for preference
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPreference(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig): AxiosPromise<Preference> {
            return localVarFp.getPreference(contextType, contextId, key, options).then((request) => request(axios, basePath));
        },
        /**
         * Set server preference store configuration
         * @summary Set server preference store configuration
         * @param {PreferenceRequest} preferenceRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setPrefrence(preferenceRequest: PreferenceRequest, options?: RawAxiosRequestConfig): AxiosPromise<Preference> {
            return localVarFp.setPrefrence(preferenceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServerPreferenceApi - object-oriented interface
 */
export class ServerPreferenceApi extends BaseAPI {
    /**
     * Remove server preference store configuration
     * @summary Remove server preference store configuration
     * @param {string} contextType 
     * @param {string} contextId 
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePrefrence(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig) {
        return ServerPreferenceApiFp(this.configuration).deletePrefrence(contextType, contextId, key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all preferneces
     * @summary Fetch all Preference Configurations Paginated
     * @param {number} size 
     * @param {number} [page] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fetchPreferences(size: number, page?: number, options?: RawAxiosRequestConfig) {
        return ServerPreferenceApiFp(this.configuration).fetchPreferences(size, page, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get server preference store configuration
     * @summary Get server preference store configuration
     * @param {string} contextType Context type for preference
     * @param {string} contextId Context Id of context type provided
     * @param {string} key Key name for preference
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPreference(contextType: string, contextId: string, key: string, options?: RawAxiosRequestConfig) {
        return ServerPreferenceApiFp(this.configuration).getPreference(contextType, contextId, key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set server preference store configuration
     * @summary Set server preference store configuration
     * @param {PreferenceRequest} preferenceRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setPrefrence(preferenceRequest: PreferenceRequest, options?: RawAxiosRequestConfig) {
        return ServerPreferenceApiFp(this.configuration).setPrefrence(preferenceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

