/* tslint:disable */
/* eslint-disable */
/**
 * Configuration Management
 * Collection of all Configuration Management Requests
 *
 * The version of the OpenAPI document: v6.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CommonResponseVaultAuthDetailsVoid } from '../models';
// @ts-ignore
import type { ExceptionBody } from '../models';
// @ts-ignore
import type { UpsertVaultAuthDetailsRequest } from '../models';
/**
 * VaultAuthDetailsApi - axios parameter creator
 */
export const VaultAuthDetailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVaultAuthDetails: async (upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertVaultAuthDetailsRequest' is not null or undefined
            assertParamExists('addVaultAuthDetails', 'upsertVaultAuthDetailsRequest', upsertVaultAuthDetailsRequest)
            const localVarPath = `/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertVaultAuthDetailsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVaultAuthDetails1: async (upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertVaultAuthDetailsRequest' is not null or undefined
            assertParamExists('addVaultAuthDetails1', 'upsertVaultAuthDetailsRequest', upsertVaultAuthDetailsRequest)
            const localVarPath = `/v1/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertVaultAuthDetailsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultAuthDetails: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultAuthDetails1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVaultAuthDetails: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVaultAuthDetails1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVaultAuthDetails: async (upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertVaultAuthDetailsRequest' is not null or undefined
            assertParamExists('updateVaultAuthDetails', 'upsertVaultAuthDetailsRequest', upsertVaultAuthDetailsRequest)
            const localVarPath = `/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertVaultAuthDetailsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVaultAuthDetails1: async (upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertVaultAuthDetailsRequest' is not null or undefined
            assertParamExists('updateVaultAuthDetails1', 'upsertVaultAuthDetailsRequest', upsertVaultAuthDetailsRequest)
            const localVarPath = `/v1/vault-auth-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer-jwt required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication basicAuth required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertVaultAuthDetailsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VaultAuthDetailsApi - functional programming interface
 */
export const VaultAuthDetailsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = VaultAuthDetailsApiAxiosParamCreator(configuration)
    return {
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addVaultAuthDetails(upsertVaultAuthDetailsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.addVaultAuthDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addVaultAuthDetails1(upsertVaultAuthDetailsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.addVaultAuthDetails1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVaultAuthDetails(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVaultAuthDetails(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.getVaultAuthDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVaultAuthDetails1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getVaultAuthDetails1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.getVaultAuthDetails1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeVaultAuthDetails(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeVaultAuthDetails(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.removeVaultAuthDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeVaultAuthDetails1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeVaultAuthDetails1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.removeVaultAuthDetails1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateVaultAuthDetails(upsertVaultAuthDetailsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.updateVaultAuthDetails']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommonResponseVaultAuthDetailsVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateVaultAuthDetails1(upsertVaultAuthDetailsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['VaultAuthDetailsApi.updateVaultAuthDetails1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * VaultAuthDetailsApi - factory interface
 */
export const VaultAuthDetailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = VaultAuthDetailsApiFp(configuration)
    return {
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.addVaultAuthDetails(upsertVaultAuthDetailsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Add Vault Auth Details
         * @summary Add Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.addVaultAuthDetails1(upsertVaultAuthDetailsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultAuthDetails(options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.getVaultAuthDetails(options).then((request) => request(axios, basePath));
        },
        /**
         * Get Vault Auth Details
         * @summary Get Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVaultAuthDetails1(options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.getVaultAuthDetails1(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVaultAuthDetails(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeVaultAuthDetails(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove Vault Auth Details
         * @summary Remove Vault Auth Details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeVaultAuthDetails1(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeVaultAuthDetails1(options).then((request) => request(axios, basePath));
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.updateVaultAuthDetails(upsertVaultAuthDetailsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Update Vault Auth Details
         * @summary Update Vault Auth Details
         * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig): AxiosPromise<CommonResponseVaultAuthDetailsVoid> {
            return localVarFp.updateVaultAuthDetails1(upsertVaultAuthDetailsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VaultAuthDetailsApi - object-oriented interface
 */
export class VaultAuthDetailsApi extends BaseAPI {
    /**
     * Add Vault Auth Details
     * @summary Add Vault Auth Details
     * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).addVaultAuthDetails(upsertVaultAuthDetailsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Add Vault Auth Details
     * @summary Add Vault Auth Details
     * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).addVaultAuthDetails1(upsertVaultAuthDetailsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Vault Auth Details
     * @summary Get Vault Auth Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVaultAuthDetails(options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).getVaultAuthDetails(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get Vault Auth Details
     * @summary Get Vault Auth Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getVaultAuthDetails1(options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).getVaultAuthDetails1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Vault Auth Details
     * @summary Remove Vault Auth Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeVaultAuthDetails(options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).removeVaultAuthDetails(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove Vault Auth Details
     * @summary Remove Vault Auth Details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeVaultAuthDetails1(options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).removeVaultAuthDetails1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Vault Auth Details
     * @summary Update Vault Auth Details
     * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateVaultAuthDetails(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).updateVaultAuthDetails(upsertVaultAuthDetailsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update Vault Auth Details
     * @summary Update Vault Auth Details
     * @param {UpsertVaultAuthDetailsRequest} upsertVaultAuthDetailsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateVaultAuthDetails1(upsertVaultAuthDetailsRequest: UpsertVaultAuthDetailsRequest, options?: RawAxiosRequestConfig) {
        return VaultAuthDetailsApiFp(this.configuration).updateVaultAuthDetails1(upsertVaultAuthDetailsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

