/**
 * Joins the scenario catalog against a Vitest JSON run and writes
 * `docs/INTERACTION_DETAILS_TEST_RESULTS.md`.
 *
 * The point is traceability in the direction that matters: not "which tests
 * ran" — Vitest already says that — but "which documented API state is
 * currently unproven". A state that exists in
 * `docs/INTERACTION_DETAILS_API_STATES.md` and in the catalog but in no test
 * name shows up as a gap here, so the doc and the suite can't quietly drift
 * apart.
 *
 * Run via `npm run test:report`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { API_META, ALL_API_IDS, SCENARIOS } from '../src/test/scenarios/index.ts';
import type { ApiId, Scenario } from '../src/test/scenarios/types.ts';

const ROOT = process.cwd();
const REPORT_JSON = path.join(ROOT, '.vitest-report.json');
const OUTPUT = path.join(ROOT, 'docs/INTERACTION_DETAILS_TEST_RESULTS.md');
const DOC = 'INTERACTION_DETAILS_API_STATES.md';

interface AssertionResult {
  ancestorTitles: string[];
  fullName: string;
  title: string;
  status: 'passed' | 'failed' | 'pending' | 'skipped' | 'todo';
  duration?: number;
  failureMessages: string[];
}

interface FileResult {
  name: string;
  status: string;
  assertionResults: AssertionResult[];
}

interface VitestJson {
  numTotalTests: number;
  numPassedTests: number;
  numFailedTests: number;
  numPendingTests: number;
  startTime: number;
  success: boolean;
  testResults: FileResult[];
}

type Verdict = 'passed' | 'failed' | 'skipped' | 'uncovered';

interface ScenarioRow {
  scenario: Scenario;
  verdict: Verdict;
  tests: Array<{ file: string; fullName: string; status: AssertionResult['status'] }>;
}

/**
 * Scenario ids share prefixes (`TL-200` vs `TL-200-empty`), so a plain
 * `includes` would credit the shorter id with the longer one's test. The id
 * must not be followed by another id character.
 */
function mentions(text: string, id: string): boolean {
  const escaped = id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|[^A-Za-z0-9-])${escaped}(?![A-Za-z0-9-])`).test(text);
}

function loadRun(): VitestJson {
  try {
    return JSON.parse(readFileSync(REPORT_JSON, 'utf-8')) as VitestJson;
  } catch {
    throw new Error(
      `No Vitest JSON at ${path.relative(ROOT, REPORT_JSON)} — run \`npm run test:report\`.`,
    );
  }
}

function verdictFor(statuses: AssertionResult['status'][]): Verdict {
  if (!statuses.length) return 'uncovered';
  if (statuses.includes('failed')) return 'failed';
  if (statuses.includes('passed')) return 'passed';
  return 'skipped';
}

function buildRows(run: VitestJson): ScenarioRow[] {
  const tests = run.testResults.flatMap((file) =>
    file.assertionResults.map((assertion) => ({
      file: path.relative(ROOT, file.name),
      fullName: assertion.fullName,
      status: assertion.status,
    })),
  );

  return SCENARIOS.map((scenario) => {
    const matched = tests.filter((test) => mentions(test.fullName, scenario.id));
    return {
      scenario,
      verdict: verdictFor(matched.map((test) => test.status)),
      tests: matched,
    };
  });
}

const MARK: Record<Verdict, string> = {
  passed: 'pass',
  failed: 'FAIL',
  skipped: 'skipped',
  uncovered: '—',
};

function stateLabel(scenario: Scenario): string {
  const { state, errorCode } = scenario;
  const base = typeof state === 'number' ? String(state) : state;
  return errorCode ? `${base} · \`${errorCode}\`` : base;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function render(run: VitestJson, rows: ScenarioRow[]): string {
  const byApi = new Map<ApiId, ScenarioRow[]>();
  for (const row of rows) {
    const list = byApi.get(row.scenario.api) ?? [];
    list.push(row);
    byApi.set(row.scenario.api, list);
  }

  const documented = rows.filter((row) => API_META[row.scenario.api].docNumber !== null);
  const covered = documented.filter((row) => row.verdict !== 'uncovered');
  const failed = rows.filter((row) => row.verdict === 'failed');
  const uncovered = documented.filter((row) => row.verdict === 'uncovered');

  const lines: string[] = [
    '# Interaction Details — API state test results',
    '',
    '<!-- Generated by `npm run test:report`. Do not edit by hand. -->',
    '',
    `Run at ${new Date(run.startTime).toISOString()}.`,
    '',
    `Every state in [\`${DOC}\`](./${DOC}) is transcribed into the scenario catalog`,
    '(`src/test/scenarios/`) and served by MSW to the real axios instance, generated',
    'clients, interceptors, thunks and reducers. A scenario counts as covered when its',
    'id appears in a test name, which is why test names lead with the id.',
    '',
    '## Summary',
    '',
    '| | |',
    '| --- | --- |',
    `| Tests | ${run.numPassedTests} passed, ${run.numFailedTests} failed, ${run.numPendingTests} pending (${run.numTotalTests} total) |`,
    `| Documented states | ${covered.length} of ${documented.length} covered |`,
    `| Failing states | ${failed.length} |`,
    `| Catalog scenarios | ${rows.length} across ${byApi.size} endpoints |`,
    '',
  ];

  if (failed.length) {
    lines.push(
      '## Failing states',
      '',
      'These are assertion failures, not gaps — a state whose behaviour has changed.',
      '',
    );
    for (const row of failed) {
      lines.push(`- \`${row.scenario.id}\` — ${escapeCell(row.scenario.title)}`);
      for (const test of row.tests.filter((t) => t.status === 'failed')) {
        lines.push(`  - ${test.file} · ${escapeCell(test.fullName)}`);
      }
    }
    lines.push('');
  }

  if (uncovered.length) {
    lines.push(
      '## Uncovered documented states',
      '',
      'In the doc and in the catalog, but named by no test.',
      '',
    );
    for (const row of uncovered) {
      const meta = API_META[row.scenario.api];
      lines.push(
        `- \`${row.scenario.id}\` (#${meta.docNumber} ${meta.label}) — ${escapeCell(row.scenario.title)}`,
      );
    }
    lines.push('');
  }

  lines.push('## Coverage by endpoint', '');

  const ordered = [...ALL_API_IDS].sort((a, b) => {
    const left = API_META[a].docNumber;
    const right = API_META[b].docNumber;
    if (left === null && right === null) return a.localeCompare(b);
    if (left === null) return 1;
    if (right === null) return -1;
    return left - right;
  });

  for (const api of ordered) {
    const apiRows = byApi.get(api) ?? [];
    if (!apiRows.length) continue;
    const meta = API_META[api];
    const heading = meta.docNumber === null ? meta.label : `#${meta.docNumber} ${meta.label}`;

    lines.push(
      `### ${heading}`,
      '',
      `Backend: \`${meta.backend}\`${meta.docNumber === null ? ' · not part of the documented set' : ''}`,
      '',
      '| Scenario | State | Result | Behaviour |',
      '| --- | --- | --- | --- |',
    );

    for (const row of apiRows) {
      lines.push(
        `| \`${row.scenario.id}\` | ${stateLabel(row.scenario)} | ${MARK[row.verdict]} | ${escapeCell(row.scenario.title)} |`,
      );
    }
    lines.push('');
  }

  lines.push(
    '## Test files',
    '',
    '| File | Tests | Result |',
    '| --- | --- | --- |',
  );
  for (const file of run.testResults) {
    const failures = file.assertionResults.filter((a) => a.status === 'failed').length;
    lines.push(
      `| \`${path.relative(ROOT, file.name)}\` | ${file.assertionResults.length} | ${
        failures ? `${failures} failed` : 'pass'
      } |`,
    );
  }
  lines.push('');

  return lines.join('\n');
}

const run = loadRun();
const rows = buildRows(run);
writeFileSync(OUTPUT, render(run, rows), 'utf-8');

const coveredDocumented = rows.filter(
  (row) => API_META[row.scenario.api].docNumber !== null && row.verdict !== 'uncovered',
).length;
const totalDocumented = rows.filter(
  (row) => API_META[row.scenario.api].docNumber !== null,
).length;

console.log(
  `${path.relative(ROOT, OUTPUT)}: ${coveredDocumented}/${totalDocumented} documented states covered, ` +
    `${run.numPassedTests}/${run.numTotalTests} tests passed`,
);
